## Group Items

### Items Object Map

The `items` type has the
[mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) above:

```javascript
'items': {
  'properties': {
    'created_at': {
      'type': 'date'
    },
    'sku': {
      'type': 'keyword'
    },
    'name': {
      'type': 'text'
    },
    'slug': {
      'type': 'keyword'
    },
    'permalink': {
      'type': 'keyword',
      'index': false
    },
    'mobile_link': {
      'type': 'keyword',
      'index': false
    },
    'status': {
      'type': 'keyword'
    },
    'available': {
      'type': 'boolean'
    },
    'visible': {
      'type': 'boolean'
    },
    'ad_relevance': {
      'type': 'byte'
    },
    'ad_type': {
      'type': 'keyword'
    },
    'short_description': {
      'type': 'text',
      'index': false
    },
    'price': {
      'type': 'float'
    },
    'price_effective_date': {
      'properties': {
        'start': {
          'type': 'date'
        },
        'end': {
          'type': 'date'
        }
      }
    },
    'base_price': {
      'type': 'float'
    },
    'currency_id': {
      'type': 'keyword',
      'index': false
    },
    'currency_symbol': {
      'type': 'keyword',
      'index': false
    },
    'quantity': {
      'type': 'float'
    },
    'measurement': {
      'enabled': false
    },
    'condition': {
      'type': 'keyword'
    },
    'warranty': {
      'type': 'keyword'
    },
    'specs': {
      'type': 'nested',
      'properties': {
        'grid': {
          'type': 'keyword'
        },
        'text': {
          'type': 'keyword'
        }
      }
    },
    'pictures': {
      'enabled': false
    },
    'installments': {
      'enabled': false
    },
    'discount': {
      'enabled': false
    },
    'views': {
      'type': 'integer'
    },
    'sales': {
      'type': 'integer'
    },
    'brands': {
      'properties': {
        '_id': {
          'type': 'keyword'
        },
        'name': {
          'type': 'keyword'
        },
        'slug': {
          'type': 'keyword'
        }
      }
    },
    'categories': {
      'properties': {
        '_id': {
          'type': 'keyword'
        },
        'name': {
          'type': 'keyword'
        },
        'slug': {
          'type': 'keyword'
        }
      }
    },
    'keywords': {
      'type': 'text'
    },
    // map variations as product nested object
    'variations': {
      'type': 'nested',
      'properties': {
        'sku': {
          'type': 'keyword'
        },
        'name': {
          'type': 'keyword'
        },
        'price': {
          'type': 'float'
        },
        'price_effective_date': {
          'properties': {
            'start': {
              'type': 'date'
            },
            'end': {
              'type': 'date'
            }
          }
        },
        'base_price': {
          'type': 'float'
        },
        'installments': {
          'enabled': false
        },
        'discount': {
          'enabled': false
        },
        'quantity': {
          'type': 'float'
        },
        'picture_id': {
          'type': 'keyword',
          'index': false
        }
      }
    }
  }
}
```

Note that the item object is similar to the
[Product Object](https://ecomstore.docs.apiary.io/#reference/products/product-object),
but with less properties and converting `specifications` object to `specs` array of nested objects

### Items Search [/items.json]

#### Simple Search [GET /items.json?q={field}:{value}]

ELS [URI Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html)

+ Parameters
    + field: keywords (string, required) - Valid item object property
    + value: tshirt (string, required) - Value to be searched

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

        {
          "took": 1,
          "timed_out": false,
          "_shards": {
            "total": 6,
            "successful": 6,
            "skipped": 0,
            "failed": 0
          },
          "hits": {
            "total": 1,
            "max_score": 1.3862944,
            "hits": [
              {
                "_index": "100",
                "_type": "items",
                "_id": "123a5432109876543210cdef",
                "_score": 1.3862944,
                "_source": {
                  "created_at": "2017-12-01T01:00:30.500Z",
                  "sku": "s-MP_2B4",
                  "name": "Mens Pique Polo Shirt",
                  "slug": "mens-pique-polo-shirt",
                  "available": true,
                  "visible": true,
                  "ad_relevance": 0,
                  "views": 1131,
                  "sales": 25,
                  "price": 42.9,
                  "price_effective_date": {
                    "end": "2018-12-01T10:00:00.000Z"
                  },
                  "base_price": 60,
                  "quantity": 100,
                  "condition": "new",
                  "specs": [
                    {
                      "key": "age_group",
                      "value": "Adult"
                    },
                    {
                      "key": "gender",
                      "value": "Male"
                    },
                    {
                      "key": "size"
                      "value": "Large"
                    },
                    {
                      "key": "size_type",
                      "value": "Regular"
                    },
                    {
                      "key": "size_system"
                      "value": "BR"
                    },
                    {
                      "key": "material",
                      "value": "Cotton"
                    },
                    {
                      "key": "colors",
                      "value": "Pique"
                    }
                  ],
                  "keywords": [
                    "tshirt",
                    "t-shirt",
                    "man"
                  ],
                  "brands": [
                    {
                      "_id": "a10000000000000000000001",
                      "name": "Shirts Example",
                      "slug": "shirts-example",
                      "logo": {
                        "url": "https://mycdn.com/shirts-example.jpg",
                        "size": "100x50"
                      }
                    }
                  ],
                  "categories": [
                    {
                      "_id": "f10000000000000000000001",
                      "name": "Polo Shirts",
                      "slug": "polo"
                    }
                  ]
                }
              }
            ]
          }
        }

#### Complex Search [POST]

ELS [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html)

+ Request (application/json)

    + Headers

            X-Store-ID: 100

    + Body

            {
              "query": {
                "bool": {
                  "must": {
                    "multi_match": {
                      "query": "tshirt",
                      "fields": [
                        "name",
                        "keywords"
                      ]
                    }
                  },
                  "filter": [
                    {
                      "term": {
                        "visible": true
                      }
                    }
                  ]
                }
              },
              "sort": [
                {
                  "available": {
                    "order": "desc"
                  }
                },
                "_score",
                {
                  "ad_relevance": {
                    "order": "desc"
                  }
                },
                {
                  "views": {
                    "order": "desc"
                  }
                }
              ]
            }

+ Response 200 (application/json)

        {
          "took": 1,
          "timed_out": false,
          "_shards": {
            "total": 6,
            "successful": 6,
            "skipped": 0,
            "failed": 0
          },
          "hits": {
            "total": 1,
            "max_score": 1.3862944,
            "hits": [
              {
                "_index": "100",
                "_type": "items",
                "_id": "123a5432109876543210cdef",
                "_score": 1.3862944,
                "_source": {
                  "created_at": "2017-12-01T01:00:30.500Z",
                  "sku": "s-MP_2B4",
                  "name": "Mens Pique Polo Shirt",
                  "slug": "mens-pique-polo-shirt",
                  "available": true,
                  "visible": true,
                  "ad_relevance": 0,
                  "views": 1131,
                  "sales": 25,
                  "price": 42.9,
                  "price_effective_date": {
                    "end": "2018-12-01T10:00:00.000Z"
                  },
                  "base_price": 60,
                  "quantity": 100,
                  "condition": "new",
                  "specs": [
                    {
                      "key": "age_group",
                      "value": "Adult"
                    },
                    {
                      "key": "gender",
                      "value": "Male"
                    },
                    {
                      "key": "size"
                      "value": "Large"
                    },
                    {
                      "key": "size_type",
                      "value": "Regular"
                    },
                    {
                      "key": "size_system"
                      "value": "BR"
                    },
                    {
                      "key": "material",
                      "value": "Cotton"
                    },
                    {
                      "key": "colors",
                      "value": "Pique"
                    }
                  ],
                  "keywords": [
                    "tshirt",
                    "t-shirt",
                    "man"
                  ],
                  "brands": [
                    {
                      "_id": "a10000000000000000000001",
                      "name": "Shirts Example",
                      "slug": "shirts-example",
                      "logo": {
                        "url": "https://mycdn.com/shirts-example.jpg",
                        "size": "100x50"
                      }
                    }
                  ],
                  "categories": [
                    {
                      "_id": "f10000000000000000000001",
                      "name": "Polo Shirts",
                      "slug": "polo"
                    }
                  ]
                }
              }
            ]
          }
        }
