+ Attributes (object)
    + `_id` (string, required) - Category ID - RegEx pattern: **`^[a-f0-9]{24}$`**
    + `name` (string, required) - Category name - Max length: **255**
    + `slug` (string) - Category page slug - Max length: **255** - RegEx pattern: **`^[a-z0-9]([a-z0-9-_./]+)?$`**
    + `ml_category_id` (string) - ID in Mercado Libre Taxonomy - RegEx pattern: **`^ML[A-Z][0-9]{2,9}$`**
    + `google_product_category_id` (number) - ID in Google Taxonomy - Mininum: **1** - Maximum: **999999999999**
