+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "available",
                  "completed",
                  "subtotal"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "2ca000000000000000000001",
                  "available": true,
                  "completed": false,
                  "subtotal": 102.90
                },
                {
                  "_id": "2ca000000000000000000002",
                  "available": true,
                  "completed": true,
                  "subtotal": 50.75
                },
                {
                  "_id": "2ca000000000000000000003",
                  "available": true,
                  "completed": false,
                  "subtotal": 171.60
                },
                {
                  "_id": "2ca000000000000000000004",
                  "available": false,
                  "completed": true,
                  "subtotal": 85.80
                },
                {
                  "_id": "2ca000000000000000000005",
                  "available": true,
                  "completed": false,
                  "subtotal": 100
                },
                {
                  "_id": "2ca000000000000000000006",
                  "available": true,
                  "completed": false,
                  "subtotal": 102.90
                },
                {
                  "_id": "2ca000000000000000000007",
                  "available": false,
                  "completed": false,
                  "subtotal": 101.90
                },
                {
                  "_id": "2ca000000000000000000008",
                  "available": true,
                  "completed": true,
                  "subtotal": 60
                },
                {
                  "_id": "2ca000000000000000000009",
                  "available": true,
                  "completed": false,
                  "subtotal": 400
                },
                {
                  "_id": "2ca000000000000000000000",
                  "available": true,
                  "completed": false,
                  "subtotal": 220.45
                }
              ]
            }
