## Group Carts

`.carts`

Use the **carts** resource to create, read, update and delete shopping carts in
a merchant's store, you can edit all cart properties and also work with all
cart subresources directly at this resource

### Cart Object [/carts/schema.json]

+ Attributes (object)
    + `available`: true (boolean) - Whether cart still available to complete checkout
    + `completed`: false (boolean) - If the cart has been completed, generating an order
    + `permalink` (string) - URL to this cart's page - Max length: **255** - Format: **uri**
    + `mobile_link` (string) - Optional URL specific to mobile devices - Max length: **255** - Format: **uri**
    + `status` (string) - Status defined by seller - Max length: **50**
    + `utm` (object) - UTM campaign HTTP parameters
        + `source` (string) - Parameter "`utm_source`", the referrer: (e.g. google, newsletter) - Max length: **100**
        + `medium` (string) - Parameter "`utm_medium`", the marketing medium: (e.g. cpc, banner, email) - Max length: **100**
        + `campaign` (string) - Parameter "`utm_campaign`", the product, promo code, or slogan (e.g. `spring_sale`) - Max length: **200**
        + `term` (string) - Parameter "`utm_term`", identifies the paid keywords - Max length: **100**
        + `content` (string) - Parameter "`utm_content`", used to differentiate ads - Max length: **255**
    + `referring_site` (string) - The website that the customer clicked on to come to the shop - Max length: **255** - Format: **uri**
    + `affiliate_code` (string) - Code to identify the affiliate that referred the customer - Max length: **200**
    + `gifts_list_owner_id` (string) - If cart is originated from a gifts list, specify customer ID who will receive the gift - RegEx pattern: **`^[a-f0-9]{24}$`**
    + `customers` (array) - List of customers associated with this cart - Max elements: **3000**
        + (string) - Customer ID
    + `other_customers`: true (boolean) - Whether cart is available for other customers too (anyone)
    + `items` (array, required) - Products composing the cart - Max elements: **3000**
        + (object) - One of the cart items
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `product_id` (string, required) - Product ID - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `variation_id` (string) - ID to specify the variation added to cart, if product has variations - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `sku` (string) - Product or variation unique reference code - Min length: **2** - Max length: **100** - RegEx pattern: **`^[A-Za-z0-9-_.]+$`**
            + `name` (string) - Product or variation full name, or other label for this cart item - Max length: **255**
            + `picture` (object) - Product or variation picture for this cart item
                + `^small|normal|big|zoom|custom$` (object) - Image size variation
                    + `url` (string, required) - Image link - Max length: **255** - Format: **uri**
                    + `size` (string) - Image size (width x height) in px, such as 100x50 (100px width, 50px height) - Max length: **11** - RegEx pattern: **`^[1-9]([0-9]+)?x[1-9]([0-9]+)?$`**
                    + `alt` (string) - Alternative text, HTML alt tag (important for SEO) - Max length: **255**
            + `customizations` (array) - Item customization fields - Max elements: **100**
                + (object) - Customization field
                    + `_id` (string, required) - Customization field ID - RegEx pattern: **`^[a-f0-9]{24}$`**
                    + `label` (string) - Title for this customization field, can be the grid title - Max length: **70**
                    + `option` (object, required) - Option chosen or created by customer
                        + `option_id` (string) - Identify option if it was predefined (not custom value created by customer) - RegEx pattern: **`^[a-z0-9_]{2,30}$`**
                        + `text` (string, required) - Option text value displayed for the client - Max length: **70**
                        + `colors` (array) - Option color palette (if the field involves colors), starting by main color - Max elements: **6**
                            + (string) - RGB code with #
                    + `attachment` (string) - URL of file attached by customer to this field - Max length: **255** - Format: **uri**
                    + `add_to_price` (object) - Price alteration due to this customization
                        + `type`: percentage (enum) - Type of price addition
                            + `percentage` (string)
                            + `fixed` (string)
                        + `addition` (number, required) - Additional value, could be negative - Mininum: **-99999999** - Maximum: **99999999** - Max precision: **0.0001**
            + `gift_wrap` (object) - Gift wrap chosen by customer
                + `tag` (string) - Tag to identify object, use only lowercase letters, digits and underscore - Max length: **20** - RegEx pattern: **`^[a-z0-9_]+$`**
                + `label` (string, required) - Title describing this gift wrap - Max length: **70**
                + `add_to_price` (number) - Additional value due to this gift wrap - Mininum: **0** - Maximum: **99999999** - Max precision: **0.0001**
            + `quantity` (number, required) - Item quantity in cart - Mininum: **0** - Maximum: **9999999** - Max precision: **0.0001**
            + `min_quantity` (number) - Minimum item quantity for this cart - Mininum: **0** - Maximum: **999999** - Max precision: **0.0001**
            + `max_quantity` (number) - Maximum item quantity for this cart - Mininum: **0** - Maximum: **9999999** - Max precision: **0.0001**
            + `keep_item_quantity`: false (boolean) - True if product quantity should not be checked, using quantity specified for this item
            + `currency_id`: BRL (string) - Designator of currency according to ISO 4217 (3 uppercase letters) - RegEx pattern: **`^[A-Z]{3}$`**
            + `currency_symbol`: R$ (string) - Graphic symbol used as a shorthand for currency's name - Max length: **20**
            + `price` (number, required) - Product sale price specifically for this cart - Mininum: **0** - Maximum: **999999999** - Max precision: **0.00001**
            + `final_price` (number) - Final item price including additions due to customizations and gift wrap - Mininum: **0** - Maximum: **999999999** - Max precision: **0.00001**
            + `keep_item_price`: false (boolean) - True if the product price should not be checked, using price specified for this item
            + `flags` (array) - Flags to associate additional info - Max elements: **10**
                + (string) - Flag title
    + `subtotal` (number, required) - The sum of all items prices - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
    + `discount` (object) - Default discount to be applied
        + `apply_at`: subtotal (enum) - In which value the discount will be applied at checkout
            + `total` (string)
            + `subtotal` (string)
            + `freight` (string)
        + `type`: percentage (enum) - Discount type
            + `percentage` (string)
            + `fixed` (string)
        + `value` (number, required) - Discount value, percentage or fixed - Mininum: **-99999999** - Maximum: **99999999** - Max precision: **0.0001**
    + `orders` (array) - List of orders completed with this cart - Max elements: **3000**
        + (string) - Order ID
    + `metafields` (array) - List of custom attributes - Max elements: **100**
        + (object) - Custom attribute object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `namespace` (string) - String to help distinguish who (or which app) created and can use the metafield - Max length: **30**
            + `field` (string) - Field name - Max length: **50**
            + `value` (string, required) - Custom property value - Max length: **255**
    + `flags` (array) - Flags to associate additional info - Max elements: **10**
        + (string) - Flag title
    + `notes` (string) - Optional notes with additional info about this cart - Max length: **255**

#### JSON Schema [GET]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Carts",
                "description": "Shopping cart object model",
                "type": "object",
                "required": [
                    "items",
                    "subtotal"
                ],
                "additionalProperties": false,
                "properties": {
                    "available": {
                        "type": "boolean",
                        "default": true,
                        "description": "Whether cart still available to complete checkout"
                    },
                    "completed": {
                        "type": "boolean",
                        "default": false,
                        "description": "If the cart has been completed, generating an order"
                    },
                    "permalink": {
                        "type": "string",
                        "maxLength": 255,
                        "format": "uri",
                        "description": "URL to this cart's page"
                    },
                    "mobile_link": {
                        "type": "string",
                        "maxLength": 255,
                        "format": "uri",
                        "description": "Optional URL specific to mobile devices"
                    },
                    "status": {
                        "type": "string",
                        "maxLength": 50,
                        "description": "Status defined by seller"
                    },
                    "utm": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "source": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Parameter \"utm_source\", the referrer: (e.g. google, newsletter)"
                            },
                            "medium": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Parameter \"utm_medium\", the marketing medium: (e.g. cpc, banner, email)"
                            },
                            "campaign": {
                                "type": "string",
                                "maxLength": 200,
                                "description": "Parameter \"utm_campaign\", the product, promo code, or slogan (e.g. spring_sale)"
                            },
                            "term": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Parameter \"utm_term\", identifies the paid keywords"
                            },
                            "content": {
                                "type": "string",
                                "maxLength": 255,
                                "description": "Parameter \"utm_content\", used to differentiate ads"
                            }
                        },
                        "description": "UTM campaign HTTP parameters"
                    },
                    "referring_site": {
                        "type": "string",
                        "maxLength": 255,
                        "format": "uri",
                        "description": "The website that the customer clicked on to come to the shop"
                    },
                    "affiliate_code": {
                        "type": "string",
                        "maxLength": 200,
                        "description": "Code to identify the affiliate that referred the customer"
                    },
                    "gifts_list_owner_id": {
                        "type": "string",
                        "pattern": "^[a-f0-9]{24}$",
                        "description": "If cart is originated from a gifts list, specify customer ID who will receive the gift"
                    },
                    "customers": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 3000,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Customer ID"
                        },
                        "description": "List of customers associated with this cart"
                    },
                    "other_customers": {
                        "type": "boolean",
                        "default": true,
                        "description": "Whether cart is available for other customers too (anyone)"
                    },
                    "items": {
                        "type": "array",
                        "maxItems": 3000,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "product_id",
                                "quantity",
                                "price"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "product_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Product ID"
                                },
                                "variation_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "ID to specify the variation added to cart, if product has variations"
                                },
                                "sku": {
                                    "type": "string",
                                    "minLength": 2,
                                    "maxLength": 100,
                                    "pattern": "^[A-Za-z0-9-_.]+$",
                                    "description": "Product or variation unique reference code"
                                },
                                "name": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Product or variation full name, or other label for this cart item"
                                },
                                "picture": {
                                    "type": "object",
                                    "additionalProperties": false,
                                    "patternProperties": {
                                        "^small|normal|big|zoom|custom$": {
                                            "type": "object",
                                            "required": [
                                                "url"
                                            ],
                                            "additionalProperties": false,
                                            "properties": {
                                                "url": {
                                                    "type": "string",
                                                    "maxLength": 255,
                                                    "format": "uri",
                                                    "description": "Image link"
                                                },
                                                "size": {
                                                    "type": "string",
                                                    "maxLength": 11,
                                                    "pattern": "^[1-9]([0-9]+)?x[1-9]([0-9]+)?$",
                                                    "description": "Image size (width x height) in px, such as 100x50 (100px width, 50px height)"
                                                },
                                                "alt": {
                                                    "type": "string",
                                                    "maxLength": 255,
                                                    "description": "Alternative text, HTML alt tag (important for SEO)"
                                                }
                                            },
                                            "description": "Image size variation"
                                        }
                                    },
                                    "description": "Product or variation picture for this cart item"
                                },
                                "customizations": {
                                    "type": "array",
                                    "maxItems": 100,
                                    "items": {
                                        "type": "object",
                                        "required": [
                                            "_id",
                                            "option"
                                        ],
                                        "additionalProperties": false,
                                        "properties": {
                                            "_id": {
                                                "type": "string",
                                                "pattern": "^[a-f0-9]{24}$",
                                                "description": "Customization field ID"
                                            },
                                            "label": {
                                                "type": "string",
                                                "maxLength": 70,
                                                "description": "Title for this customization field, can be the grid title"
                                            },
                                            "option": {
                                                "type": "object",
                                                "required": [
                                                    "text"
                                                ],
                                                "additionalProperties": false,
                                                "properties": {
                                                    "option_id": {
                                                        "type": "string",
                                                        "pattern": "^[a-z0-9_]{2,30}$",
                                                        "description": "Identify option if it was predefined (not custom value created by customer)"
                                                    },
                                                    "text": {
                                                        "type": "string",
                                                        "maxLength": 70,
                                                        "description": "Option text value displayed for the client"
                                                    },
                                                    "colors": {
                                                        "type": "array",
                                                        "maxItems": 6,
                                                        "items": {
                                                            "type": "string",
                                                            "pattern": "^#[a-f0-9]{6}$",
                                                            "description": "RGB code with #"
                                                        },
                                                        "description": "Option color palette (if the field involves colors), starting by main color"
                                                    }
                                                },
                                                "description": "Option chosen or created by customer"
                                            },
                                            "attachment": {
                                                "type": "string",
                                                "maxLength": 255,
                                                "format": "uri",
                                                "description": "URL of file attached by customer to this field"
                                            },
                                            "add_to_price": {
                                                "type": "object",
                                                "required": [
                                                    "addition"
                                                ],
                                                "additionalProperties": false,
                                                "properties": {
                                                    "type": {
                                                        "type": "string",
                                                        "enum": [
                                                            "percentage",
                                                            "fixed"
                                                        ],
                                                        "default": "percentage",
                                                        "description": "Type of price addition"
                                                    },
                                                    "addition": {
                                                        "type": "number",
                                                        "multipleOf": 0.0001,
                                                        "minimum": -99999999,
                                                        "maximum": 99999999,
                                                        "description": "Additional value, could be negative"
                                                    }
                                                },
                                                "description": "Price alteration due to this customization"
                                            }
                                        },
                                        "description": "Customization field"
                                    },
                                    "description": "Item customization fields"
                                },
                                "gift_wrap": {
                                    "type": "object",
                                    "required": [
                                        "label"
                                    ],
                                    "additionalProperties": false,
                                    "properties": {
                                        "tag": {
                                            "type": "string",
                                            "maxLength": 20,
                                            "pattern": "^[a-z0-9_]+$",
                                            "description": "Tag to identify object, use only lowercase letters, digits and underscore"
                                        },
                                        "label": {
                                            "type": "string",
                                            "maxLength": 70,
                                            "description": "Title describing this gift wrap"
                                        },
                                        "add_to_price": {
                                            "type": "number",
                                            "multipleOf": 0.0001,
                                            "minimum": 0,
                                            "maximum": 99999999,
                                            "description": "Additional value due to this gift wrap"
                                        }
                                    },
                                    "description": "Gift wrap chosen by customer"
                                },
                                "quantity": {
                                    "type": "number",
                                    "multipleOf": 0.0001,
                                    "minimum": 0,
                                    "maximum": 9999999,
                                    "description": "Item quantity in cart"
                                },
                                "min_quantity": {
                                    "type": "number",
                                    "multipleOf": 0.0001,
                                    "minimum": 0,
                                    "maximum": 999999,
                                    "description": "Minimum item quantity for this cart"
                                },
                                "max_quantity": {
                                    "type": "number",
                                    "multipleOf": 0.0001,
                                    "minimum": 0,
                                    "maximum": 9999999,
                                    "description": "Maximum item quantity for this cart"
                                },
                                "keep_item_quantity": {
                                    "type": "boolean",
                                    "default": false,
                                    "description": "True if product quantity should not be checked, using quantity specified for this item"
                                },
                                "currency_id": {
                                    "type": "string",
                                    "pattern": "^[A-Z]{3}$",
                                    "default": "BRL",
                                    "description": "Designator of currency according to ISO 4217 (3 uppercase letters)"
                                },
                                "currency_symbol": {
                                    "type": "string",
                                    "maxLength": 20,
                                    "default": "R$",
                                    "description": "Graphic symbol used as a shorthand for currency's name"
                                },
                                "price": {
                                    "type": "number",
                                    "multipleOf": 0.00001,
                                    "minimum": 0,
                                    "maximum": 999999999,
                                    "description": "Product sale price specifically for this cart"
                                },
                                "final_price": {
                                    "type": "number",
                                    "multipleOf": 0.00001,
                                    "minimum": 0,
                                    "maximum": 999999999,
                                    "description": "Final item price including additions due to customizations and gift wrap"
                                },
                                "keep_item_price": {
                                    "type": "boolean",
                                    "default": false,
                                    "description": "True if the product price should not be checked, using price specified for this item"
                                },
                                "flags": {
                                    "type": "array",
                                    "uniqueItems": true,
                                    "maxItems": 10,
                                    "items": {
                                        "type": "string",
                                        "maxLength": 20,
                                        "description": "Flag title"
                                    },
                                    "description": "Flags to associate additional info"
                                }
                            },
                            "description": "One of the cart items"
                        },
                        "description": "Products composing the cart"
                    },
                    "subtotal": {
                        "type": "number",
                        "multipleOf": 0.00001,
                        "minimum": 0,
                        "maximum": 9999999999,
                        "description": "The sum of all items prices"
                    },
                    "discount": {
                        "type": "object",
                        "required": [
                            "value"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "apply_at": {
                                "type": "string",
                                "enum": [
                                    "total",
                                    "subtotal",
                                    "freight"
                                ],
                                "default": "subtotal",
                                "description": "In which value the discount will be applied at checkout"
                            },
                            "type": {
                                "type": "string",
                                "enum": [
                                    "percentage",
                                    "fixed"
                                ],
                                "default": "percentage",
                                "description": "Discount type"
                            },
                            "value": {
                                "type": "number",
                                "multipleOf": 0.0001,
                                "minimum": -99999999,
                                "maximum": 99999999,
                                "description": "Discount value, percentage or fixed"
                            }
                        },
                        "description": "Default discount to be applied"
                    },
                    "orders": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 3000,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Order ID"
                        },
                        "description": "List of orders completed with this cart"
                    },
                    "metafields": {
                        "type": "array",
                        "maxItems": 100,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "value"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "namespace": {
                                    "type": "string",
                                    "maxLength": 30,
                                    "description": "String to help distinguish who (or which app) created and can use the metafield"
                                },
                                "field": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Field name"
                                },
                                "value": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Custom property value"
                                }
                            },
                            "description": "Custom attribute object"
                        },
                        "description": "List of custom attributes"
                    },
                    "flags": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 10,
                        "items": {
                            "type": "string",
                            "maxLength": 20,
                            "description": "Flag title"
                        },
                        "description": "Flags to associate additional info"
                    },
                    "notes": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Optional notes with additional info about this cart"
                    }
                }
            }

### All Carts [/carts.json{?limit,offset,sort,fields}]

*/carts.json?limit&offset&sort&fields\&[field]*

> Authentication<br>_GET_: **required**

Use [default URL parameters](#introduction/overview/url-params) (metadata)
for pagination and ordering, you can use any other parameter to query
by particular object properties

#### List All Store Carts [GET /carts.json]

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "available",
                  "completed",
                  "subtotal"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "2ca000000000000000000001",
                  "available": true,
                  "completed": false,
                  "subtotal": 102.90
                },
                {
                  "_id": "2ca000000000000000000002",
                  "available": true,
                  "completed": true,
                  "subtotal": 50.75
                },
                {
                  "_id": "2ca000000000000000000003",
                  "available": true,
                  "completed": false,
                  "subtotal": 171.60
                },
                {
                  "_id": "2ca000000000000000000004",
                  "available": false,
                  "completed": true,
                  "subtotal": 85.80
                },
                {
                  "_id": "2ca000000000000000000005",
                  "available": true,
                  "completed": false,
                  "subtotal": 100
                },
                {
                  "_id": "2ca000000000000000000006",
                  "available": true,
                  "completed": false,
                  "subtotal": 102.90
                },
                {
                  "_id": "2ca000000000000000000007",
                  "available": false,
                  "completed": false,
                  "subtotal": 101.90
                },
                {
                  "_id": "2ca000000000000000000008",
                  "available": true,
                  "completed": true,
                  "subtotal": 60
                },
                {
                  "_id": "2ca000000000000000000009",
                  "available": true,
                  "completed": false,
                  "subtotal": 400
                },
                {
                  "_id": "2ca000000000000000000000",
                  "available": true,
                  "completed": false,
                  "subtotal": 220.45
                }
              ]
            }

#### Pagination And Ordering [GET]

+ Parameters
    + limit: 4 (number, optional) - Max number of objects to return
    + offset: 4 (number, optional) - First entry to return
    + sort: `-subtotal` (string, optional) - Rules to order resultant objects
    + fields: `subtotal,discount` (string, optional) - Object properties to return

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 4,
                "offset": 4,
                "sort": [
                  {
                    "field": "subtotal",
                    "order": -1
                  }
                ],
                "fields": [
                  "subtotal",
                  "discount"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "2ca000000000000000000006",
                  "subtotal": 102.90,
                  "discount": {
                    "apply_at": "subtotal",
                    "type": "percentage",
                    "value": 10
                  }
                },
                {
                  "_id": "2ca000000000000000000007",
                  "subtotal": 101.90
                },
                {
                  "_id": "2ca000000000000000000005",
                  "subtotal": 100
                },
                {
                  "_id": "2ca000000000000000000004",
                  "subtotal": 85.80,
                  "discount": {
                    "apply_at": "total",
                    "type": "fixed",
                    "value": 15
                  }
                }
              ]
            }

#### Find Carts [GET /carts.json{?customers}]

+ Parameters
    + `customers`: `3c1000000000000000000005` (string, optional) - Object property to query

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "available",
                  "completed",
                  "subtotal"
                ],
                "query": {
                  "customers": "3c1000000000000000000005"
                }
              },
              "result": [
                {
                  "_id": "2ca000000000000000000008",
                  "available": true,
                  "completed": true,
                  "subtotal": 60
                }
              ]
            }

### New Cart [/carts.json]

*/carts.json*

> Authentication<br>_POST_: **required**

Request body must obey the specifications of
[this model](#reference/carts/cart-object)

#### Create New Cart [POST]

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "utm": {
                "source": "newsletter",
                "medium": "email",
                "campaign": "recovery_promo"
              },
              "customers": [
                "3c1000000000000000000001"
              ],
              "items": [
                {
                  "_id": "3130000000000000000000a1",
                  "product_id": "123a5432109876543210cdef",
                  "sku": "s-MP_2B4",
                  "name": "Mens Pique Polo Shirt",
                  "quantity": 4,
                  "price": 42.9
                },
                {
                  "_id": "3130000000000000000000a1",
                  "product_id": "1234567890abcdef01291510",
                  "sku": "COD1",
                  "name": "Sample Product Name",
                  "quantity": 1,
                  "price": 20
                }
              ],
              "subtotal": 171.6,
              "discount": {
                "apply_at": "subtotal",
                "type": "fixed",
                "value": 20
              }
            }

+ Response 201 (application/json)

    + Body

            {
              "_id": "2ca000000000000000000003"
            }

### Specific Cart [/carts/{_id}.json]

*/carts/[_id].json*

> Authentication<br>_GET_: **none**<br>_PATCH_, _PUT_, _DELETE_: **required**

In read requests, response body will follow
[this model](#reference/carts/cart-object)

For overwriting and editing, request body must obey the same specifications,
but especially for edit requests there are no required fields

#### Read Cart [GET]

+ Parameters
    + _id: 2ca000000000000000000003 (string, required) - The cart ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "_id": "2ca000000000000000000003",
              "created_at": "2017-11-19T13:10:00.612Z",
              "store_id": 100,
              "available": true,
              "completed": false,
              "utm": {
                "source": "newsletter",
                "medium": "email",
                "campaign": "recovery_promo"
              },
              "customers": [
                "3c1000000000000000000001"
              ],
              "other_customers": true,
              "items": [
                {
                  "_id": "3130000000000000000000a1",
                  "product_id": "123a5432109876543210cdef",
                  "sku": "s-MP_2B4",
                  "name": "Mens Pique Polo Shirt",
                  "quantity": 4,
                  "price": 42.9,
                  "keep_item_price": false
                },
                {
                  "_id": "3130000000000000000000a1",
                  "product_id": "1234567890abcdef01291510",
                  "sku": "COD1",
                  "name": "Sample Product Name",
                  "quantity": 1,
                  "price": 20,
                  "keep_item_price": false
                }
              ],
              "subtotal": 171.6,
              "discount": {
                "apply_at": "subtotal",
                "type": "fixed",
                "value": 20
              }
            }

#### Edit Cart [PATCH]

+ Parameters
    + _id: 2ca000000000000000000003 (string, required) - The cart ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "permalink": "https://myshop.sample/cart?i=123567788997"
            }

+ Response 204

#### Overwrite Cart [PUT]

+ Parameters
    + _id: 2ca000000000000000000003 (string, required) - The cart ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "permalink": "https://myshop.sample/cart?i=123567788997",
              "utm": {
                "source": "newsletter",
                "medium": "email",
                "campaign": "recovery_promo_2"
              },
              "customers": [
                "3c1000000000000000000001"
              ],
              "items": [
                {
                  "_id": "3130000000000000000000a1",
                  "product_id": "123a5432109876543210cdef",
                  "sku": "s-MP_2B4",
                  "name": "Mens Pique Polo Shirt",
                  "quantity": 4,
                  "price": 42.9
                },
                {
                  "_id": "3130000000000000000000a1",
                  "product_id": "1234567890abcdef01291510",
                  "sku": "COD1",
                  "name": "Sample Product Name",
                  "quantity": 1,
                  "price": 20
                }
              ],
              "subtotal": 171.6,
              "discount": {
                "apply_at": "subtotal",
                "type": "fixed",
                "value": 20
              }
            }

+ Response 204

#### Remove Cart [DELETE]

+ Parameters
    + _id: 2ca000000000000000000003 (string, required) - The cart ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 204
