+ Attributes (object)
    + `state`: registered (enum) - The state of registration, if completed, invited and waiting, or declined by customer
        + `invited` (string)
        + `registered` (string)
        + `declined` (string)
    + `enabled`: true (boolean) - Whether customer account is enabled to make orders
    + `login`: true (boolean) - Whether the customer can sign in to the store with this account
    + `status` (string) - Status defined by seller, such as active or blocked - Max length: **50**
    + `referral` (string) - ID of customer who invited this new customer, if he was invited by another account - RegEx pattern: **`^[a-f0-9]{24}$`**
    + `utm` (object) - UTM campaign HTTP parameters associated with this customer's first access
        + `source` (string) - Parameter "`utm_source`", the referrer: (e.g. google, newsletter) - Max length: **100**
        + `medium` (string) - Parameter "`utm_medium`", the marketing medium: (e.g. cpc, banner, email) - Max length: **100**
        + `campaign` (string) - Parameter "`utm_campaign`", the product, promo code, or slogan (e.g. `spring_sale`) - Max length: **200**
        + `term` (string) - Parameter "`utm_term`", identifies the paid keywords - Max length: **100**
        + `content` (string) - Parameter "`utm_content`", used to differentiate ads - Max length: **255**
    + `oauth_providers` (array) - Providers for OAuth authentication - Max elements: **20**
        + (object) - Identifiers to authorize user login
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `provider` (string, required) - The provider with which the user authenticated, eg.: facebook - Max length: **30**
            + `user_id` (string, required) - Unique ID for the user generated by the service provider - Max length: **255**
    + `locale` (string) - Customer language two letters code, sometimes with region, eg.: `pt_br`, fr, `en_us` - RegEx pattern: **`^[a-z]{2}(_[a-z]{2})?$`**
    + `main_email` (string, required) - Customer main email address - Max length: **200** - Format: **email**
    + `emails` (array) - List of customer email addresses - Max elements: **20**
        + (object) - Email object
            + `address` (string, required) - The actual email address - Max length: **200** - Format: **email**
            + `type` (enum) - The type of email
                + `home` (string)
                + `personal` (string)
                + `work` (string)
                + `other` (string)
            + `verified`: false (boolean) - States whether or not the email address has been verified
    + `accepts_marketing`: false (boolean) - Indicates whether customer would like to receive email updates from the shop
    + `display_name` (string, required) - The name of this Customer, suitable for display - Max length: **50**
    + `name` (object) - Customer name object
        + `family_name` (string) - The family name of this user, or "last name" - Max length: **70**
        + `given_name` (string) - The "first name" of this user - Max length: **70**
        + `middle_name` (string) - The middle name(s) of this user - Max length: **255**
    + `birth_date` (object) - Date of customer birth - Min properties: **1**
        + `day` (number) - Day of birth
        + `month` (number) - Number of month of birth
        + `year` (number) - Year of birth
    + `gender` (enum) - Customer gender, female, male or third gender (X)
        + `f` (string)
        + `m` (string)
        + `x` (string)
    + `photos` (array) - User profile pictures - Max elements: **20**
        + (string) - Image URL
    + `phones` (array) - List of customer phone numbers - Max elements: **20**
        + (object) - Phone object
            + `country_code` (number) - Country calling code (without `+`), defined by standards E.123 and E.164
            + `number` (string, required) - The actual phone number, digits only - Max length: **19** - RegEx pattern: **`^[0-9]+$`**
            + `type` (enum) - The type of phone
                + `home` (string)
                + `personal` (string)
                + `work` (string)
                + `other` (string)
    + `registry_type` (enum) - Physical or juridical (company) person
        + `p` (string)
        + `j` (string)
    + `doc_country` (string) - Country of document origin, an ISO 3166-2 code - Min length: **2** - Max length: **2** - RegEx pattern: **`^[A-Z]+$`**
    + `doc_number` (string) - Responsible person or organization document number (only numbers) - Max length: **19** - RegEx pattern: **`^[0-9]+$`**
    + `inscription_type` (enum) - Municipal or state registration if exists
        + `State` (string)
        + `Municipal` (string)
    + `inscription_number` (string) - Municipal or state registration number (with characters) if exists - Max length: **50**
    + `corporate_name` (string) - Registered company name or responsible fullname - Max length: **255**
    + `addresses` (array) - List of customer addresses - Max elements: **40**
        + (object) - Address object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `zip` (string, required) - ZIP (CEP, postal...) code - Max length: **30**
            + `street` (string) - Street or public place name - Max length: **200**
            + `number` (number) - House or building street number
            + `complement` (string) - Address complement or second line, such as apartment number - Max length: **100**
            + `borough` (string) - Borough name - Max length: **100**
            + `near_to` (string) - Some optional other reference for this address - Max length: **100**
            + `line_address` (string) - Full in line mailing address, should include street, number and borough - Max length: **255**
            + `city` (string) - City name - Max length: **100**
            + `country` (string) - Country name - Max length: **50**
            + `country_code` (string) - An ISO 3166-2 country code - Min length: **2** - Max length: **2** - RegEx pattern: **`^[A-Z]+$`**
            + `province` (string) - Province or state name - Max length: **100**
            + `province_code` (string) - The two-letter code for the province or state - Min length: **2** - Max length: **2** - RegEx pattern: **`^[A-Z]+$`**
            + `name` (string) - The name of recipient, generally is the customer's name - Max length: **70**
            + `last_name` (string) - The recipient's last name - Max length: **70**
            + `phone` (object) - Customer phone number for this mailing address
                + `country_code` (number) - Country calling code (without `+`), defined by standards E.123 and E.164
                + `number` (string, required) - The actual phone number, digits only - Max length: **19** - RegEx pattern: **`^[0-9]+$`**
            + `default`: false (boolean) - Indicates whether this address is the default address for the customer
    + `seller_recommendations` (array) - Lists (collections) of products recommended by seller to this customer - Max elements: **20**
        + (object) - Collection object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `title` (string) - Collection title - Max length: **50**
            + `products` (array, required) - List of products - Max elements: **100**
                + (string) - Product ID
            + `tag` (string) - Tag to identify object, use only lowercase letters, digits and underscore - Max length: **20** - RegEx pattern: **`^[a-z0-9_]+$`**
    + `lists` (array) - Lists (collections) of products selected by the customer - Max elements: **20**
        + (object) - Collection object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `title` (string) - Collection title - Max length: **50**
            + `products` (array, required) - List of products - Max elements: **300**
                + (string) - Product ID
            + `tag` (string) - Tag to identify object, use only lowercase letters, digits and underscore - Max length: **20** - RegEx pattern: **`^[a-z0-9_]+$`**
    + `ai_recommendations` (array) - Products recommended by artificial intelligence (machine learning) - Max elements: **100**
        + (string) - Product ID
    + `favorites` (array) - Products marked as favorites - Max elements: **3000**
        + (string) - Product ID
    + `gifts_list` (array) - Products added to customer's gift list - Max elements: **3000**
        + (object) - Collection object
            + `_id` (string, required) - Product ID - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `waiting`: true (boolean) - Whether the gift is waiting to buyer or has already been purchased
            + `flags` (array) - Flags to associate additional info - Max elements: **10**
                + (string) - Flag title
    + `gifts_list_info` (object) - Informations about this customer gifts list - Min properties: **1**
        + `title` (string) - Title for the gifts list, generally defined by the customer - Max length: **100**
        + `description` (string) - Short text description for the gifts list - Max length: **255**
        + `permalink` (string) - URL to gifts list page - Max length: **255** - Format: **uri**
        + `event_date` (string) - Date and time of the event in ISO 8601 standard representation - Format: **date-time**
        + `valid_thru` (string) - Validity of the list, until this date the gifts can be bought - Format: **date-time**
        + `authors` (array) - Authors of the list, if it is a wedding list, the names of the bride and groom - Max elements: **10**
            + (string) - Author name
        + `notification_email` (string) - Email address to be notified after gift purchase - Max length: **200** - Format: **email**
        + `contact` (string) - Email address or phone number to contact list owners - Max length: **200**
    + `last_visited_products` (array) - Last products visited by the customer - Max elements: **20**
        + (string) - Product ID
    + `last_searched_terms` (array) - Last terms searched on shop by the customer - Max elements: **20**
        + (string) - Term
    + `products_purchased` (array) - Items purchased with this account, on all saved (not necessarily paid) orders - Max elements: **3000**
        + (string) - Product ID
    + `discount` (object) - Default discount exclusively for this customer
        + `apply_at`: subtotal (enum) - In which value the discount will be applied at checkout
            + `total` (string)
            + `subtotal` (string)
            + `freight` (string)
        + `type`: percentage (enum) - Discount type
            + `percentage` (string)
            + `fixed` (string)
        + `value` (number, required) - Discount value, percentage or fixed - Mininum: **-99999999** - Maximum: **99999999** - Max precision: **0.0001**
    + `tax_exempt`: true (boolean) - Whether the customer should be charged taxes when placing orders
    + `currency_id`: BRL (string) - Default currency for the user, designator according to ISO 4217 (3 uppercase letters) - RegEx pattern: **`^[A-Z]{3}$`**
    + `currency_symbol`: R$ (string) - Graphic symbol used as a shorthand for currency's name - Max length: **20**
    + `orders_count` (number) - Total number of orders completed by this customer
    + `orders_total_value` (number) - The total amount in orders completed by this customer - Mininum: **0** - Maximum: **999999999999** - Max precision: **0.00001**
    + `loyalty_points` (object) - Loyalty points programs, `program_id` as property name - Max properties: **100**
        + `^[a-z0-9_]{2,30}$` (object) - Loyalty points program object, specify how many points the customer have
            + `name` (string) - The name of the loyalty points program - Max length: **50**
            + `accumulated_points` (number, required) - Number of accumulated loyalty points - Mininum: **0** - Maximum: **999999999** - Max precision: **0.00001**
    + `affiliate_code` (string) - Code to identify the affiliate that referred the customer - Max length: **200**
    + `total_spent` (number) - The total amount of money that this customer has spent at the store - Mininum: **0** - Maximum: **999999999999** - Max precision: **0.00001**
    + `total_cancelled` (number) - The total amount in cancelled orders - Mininum: **0** - Maximum: **999999999999** - Max precision: **0.00001**
    + `orders` (array) - List of customer orders - Max elements: **1000**
        + (object) - Registered order
            + `_id` (string, required) - Order ID - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `created_at` (string) - When order was saved, date and time in ISO 8601 standard representation - Format: **date-time**
            + `number` (number) - Auto incremented order number
            + `currency_id`: BRL (string) - Designator of currency according to ISO 4217 (3 uppercase letters) - RegEx pattern: **`^[A-Z]{3}$`**
            + `currency_symbol`: R$ (string) - Graphic symbol used as a shorthand for currency's name - Max length: **20**
            + `amount` (object) - Object with sums of values
                + `total` (number, required) - Order total amount - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `subtotal` (number) - The sum of all items prices - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `freight` (number) - Order freight cost - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `discount` (number) - Applied discount value - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `tax` (number) - The sum of all the taxes applied to the order - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `extra` (number) - Sum of optional extra costs applied - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
            + `payment_method_label` (string) - Name or summary of order payment method(s) - Max length: **100**
            + `shipping_method_label` (string) - Name of order shipping method(s) - Max length: **100**
    + `metafields` (array) - List of custom attributes - Max elements: **100**
        + (object) - Custom attribute object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `namespace` (string) - String to help distinguish who (or which app) created and can use the metafield - Max length: **30**
            + `field` (string) - Field name - Max length: **50**
            + `value` (string, required) - Custom property value - Max length: **255**
    + `hidden_metafields` (array) - List of custom attributes - Max elements: **100**
        + (object) - Custom attribute object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `namespace` (string) - String to help distinguish who (or which app) created and can use the metafield - Max length: **30**
            + `field` (string) - Field name - Max length: **50**
            + `value` (string, required) - Custom property value - Max length: **255**
    + `flags` (array) - Flags to associate additional info - Max elements: **10**
        + (string) - Flag title
    + `notes` (string) - Optional notes with additional info about this customer - Max length: **255**
    + `staff_notes` (string) - Description and notes about this customer, available only for shop administrators - Max length: **255**
