+ Parameters
    + _id: 3c1000000000000000000003 (string, required) - The customer ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "status": "active",
              "staff_notes": "This customer is a good person"
            }

+ Response 204
