+ Parameters
    + `main_email`: `janerue@mail.ex` (string, optional) - Object property to query

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "state",
                  "enabled",
                  "login",
                  "status",
                  "main_email",
                  "display_name"
                ],
                "query": {
                  "main_email": "janerue@mail.ex"
                }
              },
              "result": [
                {
                  "_id": "3c1000000000000000000005",
                  "state": "registered",
                  "enabled": true,
                  "login": true,
                  "status": "star",
                  "main_email": "janerue@mail.ex",
                  "display_name": "Jane Rue"
                }
              ]
            }
