+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Customers",
                "description": "Customer object model",
                "type": "object",
                "required": [
                    "main_email",
                    "display_name"
                ],
                "additionalProperties": false,
                "properties": {
                    "state": {
                        "type": "string",
                        "enum": [
                            "invited",
                            "registered",
                            "declined"
                        ],
                        "default": "registered",
                        "description": "The state of registration, if completed, invited and waiting, or declined by customer"
                    },
                    "enabled": {
                        "type": "boolean",
                        "default": true,
                        "description": "Whether customer account is enabled to make orders"
                    },
                    "login": {
                        "type": "boolean",
                        "default": true,
                        "description": "Whether the customer can sign in to the store with this account"
                    },
                    "status": {
                        "type": "string",
                        "maxLength": 50,
                        "description": "Status defined by seller, such as active or blocked"
                    },
                    "referral": {
                        "type": "string",
                        "pattern": "^[a-f0-9]{24}$",
                        "description": "ID of customer who invited this new customer, if he was invited by another account"
                    },
                    "utm": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "source": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Parameter \"utm_source\", the referrer: (e.g. google, newsletter)"
                            },
                            "medium": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Parameter \"utm_medium\", the marketing medium: (e.g. cpc, banner, email)"
                            },
                            "campaign": {
                                "type": "string",
                                "maxLength": 200,
                                "description": "Parameter \"utm_campaign\", the product, promo code, or slogan (e.g. spring_sale)"
                            },
                            "term": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Parameter \"utm_term\", identifies the paid keywords"
                            },
                            "content": {
                                "type": "string",
                                "maxLength": 255,
                                "description": "Parameter \"utm_content\", used to differentiate ads"
                            }
                        },
                        "description": "UTM campaign HTTP parameters associated with this customer's first access"
                    },
                    "oauth_providers": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "provider",
                                "user_id"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "provider": {
                                    "type": "string",
                                    "maxLength": 30,
                                    "description": "The provider with which the user authenticated, eg.: facebook"
                                },
                                "user_id": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Unique ID for the user generated by the service provider"
                                }
                            },
                            "description": "Identifiers to authorize user login"
                        },
                        "description": "Providers for OAuth authentication"
                    },
                    "locale": {
                        "type": "string",
                        "pattern": "^[a-z]{2}(_[a-z]{2})?$",
                        "description": "Customer language two letters code, sometimes with region, eg.: pt_br, fr, en_us"
                    },
                    "main_email": {
                        "type": "string",
                        "maxLength": 200,
                        "format": "email",
                        "description": "Customer main email address"
                    },
                    "emails": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "address"
                            ],
                            "properties": {
                                "address": {
                                    "type": "string",
                                    "maxLength": 200,
                                    "format": "email",
                                    "description": "The actual email address"
                                },
                                "type": {
                                    "type": "string",
                                    "enum": [
                                        "home",
                                        "personal",
                                        "work",
                                        "other"
                                    ],
                                    "description": "The type of email"
                                },
                                "verified": {
                                    "type": "boolean",
                                    "default": false,
                                    "description": "States whether or not the email address has been verified"
                                }
                            },
                            "description": "Email object"
                        },
                        "description": "List of customer email addresses"
                    },
                    "accepts_marketing": {
                        "type": "boolean",
                        "default": false,
                        "description": "Indicates whether customer would like to receive email updates from the shop"
                    },
                    "display_name": {
                        "type": "string",
                        "maxLength": 50,
                        "description": "The name of this Customer, suitable for display"
                    },
                    "name": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "family_name": {
                                "type": "string",
                                "maxLength": 70,
                                "description": "The family name of this user, or \"last name\""
                            },
                            "given_name": {
                                "type": "string",
                                "maxLength": 70,
                                "description": "The \"first name\" of this user"
                            },
                            "middle_name": {
                                "type": "string",
                                "maxLength": 255,
                                "description": "The middle name(s) of this user"
                            }
                        },
                        "description": "Customer name object"
                    },
                    "birth_date": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "day": {
                                "type": "integer",
                                "min": 1,
                                "max": 31,
                                "description": "Day of birth"
                            },
                            "month": {
                                "type": "integer",
                                "min": 1,
                                "max": 12,
                                "description": "Number of month of birth"
                            },
                            "year": {
                                "type": "integer",
                                "min": 1800,
                                "max": 2200,
                                "description": "Year of birth"
                            }
                        },
                        "description": "Date of customer birth"
                    },
                    "gender": {
                        "type": "string",
                        "enum": [
                            "f",
                            "m",
                            "x"
                        ],
                        "description": "Customer gender, female, male or third gender (X)"
                    },
                    "photos": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 20,
                        "items": {
                            "type": "string",
                            "maxLength": 255,
                            "description": "Image URL"
                        },
                        "description": "User profile pictures"
                    },
                    "phones": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "number"
                            ],
                            "properties": {
                                "country_code": {
                                    "type": "integer",
                                    "min": 1,
                                    "max": 999,
                                    "description": "Country calling code (without +), defined by standards E.123 and E.164"
                                },
                                "number": {
                                    "type": "string",
                                    "maxLength": 19,
                                    "pattern": "^[0-9]+$",
                                    "description": "The actual phone number, digits only"
                                },
                                "type": {
                                    "type": "string",
                                    "enum": [
                                        "home",
                                        "personal",
                                        "work",
                                        "other"
                                    ],
                                    "description": "The type of phone"
                                }
                            },
                            "description": "Phone object"
                        },
                        "description": "List of customer phone numbers"
                    },
                    "registry_type": {
                        "type": "string",
                        "enum": [
                            "p",
                            "j"
                        ],
                        "description": "Physical or juridical (company) person"
                    },
                    "doc_country": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 2,
                        "pattern": "^[A-Z]+$",
                        "description": "Country of document origin, an ISO 3166-2 code"
                    },
                    "doc_number": {
                        "type": "string",
                        "maxLength": 19,
                        "pattern": "^[0-9]+$",
                        "description": "Responsible person or organization document number (only numbers)"
                    },
                    "inscription_type": {
                        "type": "string",
                        "enum": [
                            "State",
                            "Municipal"
                        ],
                        "description": "Municipal or state registration if exists"
                    },
                    "inscription_number": {
                        "type": "string",
                        "maxLength": 50,
                        "description": "Municipal or state registration number (with characters) if exists"
                    },
                    "corporate_name": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Registered company name or responsible fullname"
                    },
                    "addresses": {
                        "type": "array",
                        "maxItems": 40,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "zip"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "zip": {
                                    "type": "string",
                                    "maxLength": 30,
                                    "description": "ZIP (CEP, postal...) code"
                                },
                                "street": {
                                    "type": "string",
                                    "maxLength": 200,
                                    "description": "Street or public place name"
                                },
                                "number": {
                                    "type": "integer",
                                    "min": 1,
                                    "max": 9999999,
                                    "description": "House or building street number"
                                },
                                "complement": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Address complement or second line, such as apartment number"
                                },
                                "borough": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Borough name"
                                },
                                "near_to": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Some optional other reference for this address"
                                },
                                "line_address": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Full in line mailing address, should include street, number and borough"
                                },
                                "city": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "City name"
                                },
                                "country": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Country name"
                                },
                                "country_code": {
                                    "type": "string",
                                    "minLength": 2,
                                    "maxLength": 2,
                                    "pattern": "^[A-Z]+$",
                                    "description": "An ISO 3166-2 country code"
                                },
                                "province": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Province or state name"
                                },
                                "province_code": {
                                    "type": "string",
                                    "minLength": 2,
                                    "maxLength": 2,
                                    "pattern": "^[A-Z]+$",
                                    "description": "The two-letter code for the province or state"
                                },
                                "name": {
                                    "type": "string",
                                    "maxLength": 70,
                                    "description": "The name of recipient, generally is the customer's name"
                                },
                                "last_name": {
                                    "type": "string",
                                    "maxLength": 70,
                                    "description": "The recipient's last name"
                                },
                                "phone": {
                                    "type": "object",
                                    "additionalProperties": false,
                                    "required": [
                                        "number"
                                    ],
                                    "properties": {
                                        "country_code": {
                                            "type": "integer",
                                            "min": 1,
                                            "max": 999,
                                            "description": "Country calling code (without +), defined by standards E.123 and E.164"
                                        },
                                        "number": {
                                            "type": "string",
                                            "maxLength": 19,
                                            "pattern": "^[0-9]+$",
                                            "description": "The actual phone number, digits only"
                                        }
                                    },
                                    "description": "Customer phone number for this mailing address"
                                },
                                "default": {
                                    "type": "boolean",
                                    "default": false,
                                    "description": "Indicates whether this address is the default address for the customer"
                                }
                            },
                            "description": "Address object"
                        },
                        "description": "List of customer addresses"
                    },
                    "seller_recommendations": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "products"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "title": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Collection title"
                                },
                                "products": {
                                    "type": "array",
                                    "uniqueItems": true,
                                    "maxItems": 100,
                                    "items": {
                                        "type": "string",
                                        "pattern": "^[a-f0-9]{24}$",
                                        "description": "Product ID"
                                    },
                                    "description": "List of products"
                                },
                                "tag": {
                                    "type": "string",
                                    "maxLength": 20,
                                    "pattern": "^[a-z0-9_]+$",
                                    "description": "Tag to identify object, use only lowercase letters, digits and underscore"
                                }
                            },
                            "description": "Collection object"
                        },
                        "description": "Lists (collections) of products recommended by seller to this customer"
                    },
                    "lists": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "products"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "title": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Collection title"
                                },
                                "products": {
                                    "type": "array",
                                    "uniqueItems": true,
                                    "maxItems": 300,
                                    "items": {
                                        "type": "string",
                                        "pattern": "^[a-f0-9]{24}$",
                                        "description": "Product ID"
                                    },
                                    "description": "List of products"
                                },
                                "tag": {
                                    "type": "string",
                                    "maxLength": 20,
                                    "pattern": "^[a-z0-9_]+$",
                                    "description": "Tag to identify object, use only lowercase letters, digits and underscore"
                                }
                            },
                            "description": "Collection object"
                        },
                        "description": "Lists (collections) of products selected by the customer"
                    },
                    "ai_recommendations": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 100,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Product ID"
                        },
                        "description": "Products recommended by artificial intelligence (machine learning)"
                    },
                    "favorites": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 3000,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Product ID"
                        },
                        "description": "Products marked as favorites"
                    },
                    "gifts_list": {
                        "type": "array",
                        "maxItems": 3000,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Product ID"
                                },
                                "waiting": {
                                    "type": "boolean",
                                    "default": true,
                                    "description": "Whether the gift is waiting to buyer or has already been purchased"
                                },
                                "flags": {
                                    "type": "array",
                                    "uniqueItems": true,
                                    "maxItems": 10,
                                    "items": {
                                        "type": "string",
                                        "maxLength": 20,
                                        "description": "Flag title"
                                    },
                                    "description": "Flags to associate additional info"
                                }
                            },
                            "description": "Collection object"
                        },
                        "description": "Products added to customer's gift list"
                    },
                    "gifts_list_info": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "title": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Title for the gifts list, generally defined by the customer"
                            },
                            "description": {
                                "type": "string",
                                "maxLength": 255,
                                "description": "Short text description for the gifts list"
                            },
                            "permalink": {
                                "type": "string",
                                "maxLength": 255,
                                "format": "uri",
                                "description": "URL to gifts list page"
                            },
                            "event_date": {
                                "type": "string",
                                "format": "date-time",
                                "description": "Date and time of the event in ISO 8601 standard representation"
                            },
                            "valid_thru": {
                                "type": "string",
                                "format": "date-time",
                                "description": "Validity of the list, until this date the gifts can be bought"
                            },
                            "authors": {
                                "type": "array",
                                "uniqueItems": true,
                                "maxItems": 10,
                                "items": {
                                    "type": "string",
                                    "maxLength": 70,
                                    "description": "Author name"
                                },
                                "description": "Authors of the list, if it is a wedding list, the names of the bride and groom"
                            },
                            "notification_email": {
                                "type": "string",
                                "maxLength": 200,
                                "format": "email",
                                "description": "Email address to be notified after gift purchase"
                            },
                            "contact": {
                                "type": "string",
                                "maxLength": 200,
                                "description": "Email address or phone number to contact list owners"
                            }
                        },
                        "description": "Informations about this customer gifts list"
                    },
                    "last_visited_products": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 20,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Product ID"
                        },
                        "description": "Last products visited by the customer"
                    },
                    "last_searched_terms": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 20,
                        "items": {
                            "type": "string",
                            "maxLength": 50,
                            "description": "Term"
                        },
                        "description": "Last terms searched on shop by the customer"
                    },
                    "products_purchased": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 3000,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Product ID"
                        },
                        "description": "Items purchased with this account, on all saved (not necessarily paid) orders"
                    },
                    "discount": {
                        "type": "object",
                        "required": [
                            "value"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "apply_at": {
                                "type": "string",
                                "enum": [
                                    "total",
                                    "subtotal",
                                    "freight"
                                ],
                                "default": "subtotal",
                                "description": "In which value the discount will be applied at checkout"
                            },
                            "type": {
                                "type": "string",
                                "enum": [
                                    "percentage",
                                    "fixed"
                                ],
                                "default": "percentage",
                                "description": "Discount type"
                            },
                            "value": {
                                "type": "number",
                                "multipleOf": 0.0001,
                                "minimum": -99999999,
                                "maximum": 99999999,
                                "description": "Discount value, percentage or fixed"
                            }
                        },
                        "description": "Default discount exclusively for this customer"
                    },
                    "tax_exempt": {
                        "type": "boolean",
                        "default": true,
                        "description": "Whether the customer should be charged taxes when placing orders"
                    },
                    "currency_id": {
                        "type": "string",
                        "pattern": "^[A-Z]{3}$",
                        "default": "BRL",
                        "description": "Default currency for the user, designator according to ISO 4217 (3 uppercase letters)"
                    },
                    "currency_symbol": {
                        "type": "string",
                        "maxLength": 20,
                        "default": "R$",
                        "description": "Graphic symbol used as a shorthand for currency's name"
                    },
                    "orders_count": {
                        "type": "integer",
                        "min": 0,
                        "max": 9999999,
                        "description": "Total number of orders completed by this customer"
                    },
                    "orders_total_value": {
                        "type": "number",
                        "multipleOf": 0.00001,
                        "minimum": 0,
                        "maximum": 999999999999,
                        "description": "The total amount in orders completed by this customer"
                    },
                    "loyalty_points": {
                        "type": "object",
                        "additionalProperties": false,
                        "maxProperties": 100,
                        "patternProperties": {
                            "^[a-z0-9_]{2,30}$": {
                                "type": "object",
                                "required": [
                                    "accumulated_points"
                                ],
                                "additionalProperties": false,
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "maxLength": 50,
                                        "description": "The name of the loyalty points program"
                                    },
                                    "accumulated_points": {
                                        "type": "number",
                                        "multipleOf": 0.00001,
                                        "minimum": 0,
                                        "maximum": 999999999,
                                        "description": "Number of accumulated loyalty points"
                                    }
                                },
                                "description": "Loyalty points program object, specify how many points the customer have"
                            }
                        },
                        "description": "Loyalty points programs, program_id as property name"
                    },
                    "affiliate_code": {
                        "type": "string",
                        "maxLength": 200,
                        "description": "Code to identify the affiliate that referred the customer"
                    },
                    "total_spent": {
                        "type": "number",
                        "multipleOf": 0.00001,
                        "minimum": 0,
                        "maximum": 999999999999,
                        "description": "The total amount of money that this customer has spent at the store"
                    },
                    "total_cancelled": {
                        "type": "number",
                        "multipleOf": 0.00001,
                        "minimum": 0,
                        "maximum": 999999999999,
                        "description": "The total amount in cancelled orders"
                    },
                    "orders": {
                        "type": "array",
                        "maxItems": 1000,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Order ID"
                                },
                                "created_at": {
                                    "type": "string",
                                    "format": "date-time",
                                    "description": "When order was saved, date and time in ISO 8601 standard representation"
                                },
                                "number": {
                                    "type": "integer",
                                    "min": 1,
                                    "max": 999999999,
                                    "description": "Auto incremented order number"
                                },
                                "currency_id": {
                                    "type": "string",
                                    "pattern": "^[A-Z]{3}$",
                                    "default": "BRL",
                                    "description": "Designator of currency according to ISO 4217 (3 uppercase letters)"
                                },
                                "currency_symbol": {
                                    "type": "string",
                                    "maxLength": 20,
                                    "default": "R$",
                                    "description": "Graphic symbol used as a shorthand for currency's name"
                                },
                                "amount": {
                                    "type": "object",
                                    "additionalProperties": false,
                                    "required": [
                                        "total"
                                    ],
                                    "properties": {
                                        "total": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "Order total amount"
                                        },
                                        "subtotal": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "The sum of all items prices"
                                        },
                                        "freight": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "Order freight cost"
                                        },
                                        "discount": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "Applied discount value"
                                        },
                                        "tax": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "The sum of all the taxes applied to the order"
                                        },
                                        "extra": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "Sum of optional extra costs applied"
                                        }
                                    },
                                    "description": "Object with sums of values"
                                },
                                "payment_method_label": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Name or summary of order payment method(s)"
                                },
                                "shipping_method_label": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Name of order shipping method(s)"
                                }
                            },
                            "description": "Registered order"
                        },
                        "description": "List of customer orders"
                    },
                    "metafields": {
                        "type": "array",
                        "maxItems": 100,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "value"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "namespace": {
                                    "type": "string",
                                    "maxLength": 30,
                                    "description": "String to help distinguish who (or which app) created and can use the metafield"
                                },
                                "field": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Field name"
                                },
                                "value": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Custom property value"
                                }
                            },
                            "description": "Custom attribute object"
                        },
                        "description": "List of custom attributes"
                    },
                    "hidden_metafields": {
                        "type": "array",
                        "maxItems": 100,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "value"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "namespace": {
                                    "type": "string",
                                    "maxLength": 30,
                                    "description": "String to help distinguish who (or which app) created and can use the metafield"
                                },
                                "field": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Field name"
                                },
                                "value": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Custom property value"
                                }
                            },
                            "description": "Custom attribute object"
                        },
                        "description": "List of custom attributes"
                    },
                    "flags": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 10,
                        "items": {
                            "type": "string",
                            "maxLength": 20,
                            "description": "Flag title"
                        },
                        "description": "Flags to associate additional info"
                    },
                    "notes": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Optional notes with additional info about this customer"
                    },
                    "staff_notes": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Description and notes about this customer, available only for shop administrators"
                    }
                }
            }
