## Group Customers

`.customers`

Use the **customers** resource to create, read, update and delete end users in
a merchant's store, you can edit all customer properties and also work with all
customer subresources directly at this resource

### Customer Object [/customers/schema.json]

+ Attributes (object)
    + `state`: registered (enum) - The state of registration, if completed, invited and waiting, or declined by customer
        + `invited` (string)
        + `registered` (string)
        + `declined` (string)
    + `enabled`: true (boolean) - Whether customer account is enabled to make orders
    + `login`: true (boolean) - Whether the customer can sign in to the store with this account
    + `status` (string) - Status defined by seller, such as active or blocked - Max length: **50**
    + `referral` (string) - ID of customer who invited this new customer, if he was invited by another account - RegEx pattern: **`^[a-f0-9]{24}$`**
    + `utm` (object) - UTM campaign HTTP parameters associated with this customer's first access
        + `source` (string) - Parameter "`utm_source`", the referrer: (e.g. google, newsletter) - Max length: **100**
        + `medium` (string) - Parameter "`utm_medium`", the marketing medium: (e.g. cpc, banner, email) - Max length: **100**
        + `campaign` (string) - Parameter "`utm_campaign`", the product, promo code, or slogan (e.g. `spring_sale`) - Max length: **200**
        + `term` (string) - Parameter "`utm_term`", identifies the paid keywords - Max length: **100**
        + `content` (string) - Parameter "`utm_content`", used to differentiate ads - Max length: **255**
    + `oauth_providers` (array) - Providers for OAuth authentication - Max elements: **20**
        + (object) - Identifiers to authorize user login
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `provider` (string, required) - The provider with which the user authenticated, eg.: facebook - Max length: **30**
            + `user_id` (string, required) - Unique ID for the user generated by the service provider - Max length: **255**
    + `locale` (string) - Customer language two letters code, sometimes with region, eg.: `pt_br`, fr, `en_us` - RegEx pattern: **`^[a-z]{2}(_[a-z]{2})?$`**
    + `main_email` (string, required) - Customer main email address - Max length: **200** - Format: **email**
    + `emails` (array) - List of customer email addresses - Max elements: **20**
        + (object) - Email object
            + `address` (string, required) - The actual email address - Max length: **200** - Format: **email**
            + `type` (enum) - The type of email
                + `home` (string)
                + `personal` (string)
                + `work` (string)
                + `other` (string)
            + `verified`: false (boolean) - States whether or not the email address has been verified
    + `accepts_marketing`: false (boolean) - Indicates whether customer would like to receive email updates from the shop
    + `display_name` (string, required) - The name of this Customer, suitable for display - Max length: **50**
    + `name` (object) - Customer name object
        + `family_name` (string) - The family name of this user, or "last name" - Max length: **70**
        + `given_name` (string) - The "first name" of this user - Max length: **70**
        + `middle_name` (string) - The middle name(s) of this user - Max length: **255**
    + `birth_date` (object) - Date of customer birth - Min properties: **1**
        + `day` (number) - Day of birth
        + `month` (number) - Number of month of birth
        + `year` (number) - Year of birth
    + `gender` (enum) - Customer gender, female, male or third gender (X)
        + `f` (string)
        + `m` (string)
        + `x` (string)
    + `photos` (array) - User profile pictures - Max elements: **20**
        + (string) - Image URL
    + `phones` (array) - List of customer phone numbers - Max elements: **20**
        + (object) - Phone object
            + `country_code` (number) - Country calling code (without `+`), defined by standards E.123 and E.164
            + `number` (string, required) - The actual phone number, digits only - Max length: **19** - RegEx pattern: **`^[0-9]+$`**
            + `type` (enum) - The type of phone
                + `home` (string)
                + `personal` (string)
                + `work` (string)
                + `other` (string)
    + `registry_type` (enum) - Physical or juridical (company) person
        + `p` (string)
        + `j` (string)
    + `doc_country` (string) - Country of document origin, an ISO 3166-2 code - Min length: **2** - Max length: **2** - RegEx pattern: **`^[A-Z]+$`**
    + `doc_number` (string) - Responsible person or organization document number (only numbers) - Max length: **19** - RegEx pattern: **`^[0-9]+$`**
    + `inscription_type` (enum) - Municipal or state registration if exists
        + `State` (string)
        + `Municipal` (string)
    + `inscription_number` (string) - Municipal or state registration number (with characters) if exists - Max length: **50**
    + `corporate_name` (string) - Registered company name or responsible fullname - Max length: **255**
    + `addresses` (array) - List of customer addresses - Max elements: **40**
        + (object) - Address object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `zip` (string, required) - ZIP (CEP, postal...) code - Max length: **30**
            + `street` (string) - Street or public place name - Max length: **200**
            + `number` (number) - House or building street number
            + `complement` (string) - Address complement or second line, such as apartment number - Max length: **100**
            + `borough` (string) - Borough name - Max length: **100**
            + `near_to` (string) - Some optional other reference for this address - Max length: **100**
            + `line_address` (string) - Full in line mailing address, should include street, number and borough - Max length: **255**
            + `city` (string) - City name - Max length: **100**
            + `country` (string) - Country name - Max length: **50**
            + `country_code` (string) - An ISO 3166-2 country code - Min length: **2** - Max length: **2** - RegEx pattern: **`^[A-Z]+$`**
            + `province` (string) - Province or state name - Max length: **100**
            + `province_code` (string) - The two-letter code for the province or state - Min length: **2** - Max length: **2** - RegEx pattern: **`^[A-Z]+$`**
            + `name` (string) - The name of recipient, generally is the customer's name - Max length: **70**
            + `last_name` (string) - The recipient's last name - Max length: **70**
            + `phone` (object) - Customer phone number for this mailing address
                + `country_code` (number) - Country calling code (without `+`), defined by standards E.123 and E.164
                + `number` (string, required) - The actual phone number, digits only - Max length: **19** - RegEx pattern: **`^[0-9]+$`**
            + `default`: false (boolean) - Indicates whether this address is the default address for the customer
    + `seller_recommendations` (array) - Lists (collections) of products recommended by seller to this customer - Max elements: **20**
        + (object) - Collection object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `title` (string) - Collection title - Max length: **50**
            + `products` (array, required) - List of products - Max elements: **100**
                + (string) - Product ID
            + `tag` (string) - Tag to identify object, use only lowercase letters, digits and underscore - Max length: **20** - RegEx pattern: **`^[a-z0-9_]+$`**
    + `lists` (array) - Lists (collections) of products selected by the customer - Max elements: **20**
        + (object) - Collection object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `title` (string) - Collection title - Max length: **50**
            + `products` (array, required) - List of products - Max elements: **300**
                + (string) - Product ID
            + `tag` (string) - Tag to identify object, use only lowercase letters, digits and underscore - Max length: **20** - RegEx pattern: **`^[a-z0-9_]+$`**
    + `ai_recommendations` (array) - Products recommended by artificial intelligence (machine learning) - Max elements: **100**
        + (string) - Product ID
    + `favorites` (array) - Products marked as favorites - Max elements: **3000**
        + (string) - Product ID
    + `gifts_list` (array) - Products added to customer's gift list - Max elements: **3000**
        + (object) - Collection object
            + `_id` (string, required) - Product ID - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `waiting`: true (boolean) - Whether the gift is waiting to buyer or has already been purchased
            + `flags` (array) - Flags to associate additional info - Max elements: **10**
                + (string) - Flag title
    + `gifts_list_info` (object) - Informations about this customer gifts list - Min properties: **1**
        + `title` (string) - Title for the gifts list, generally defined by the customer - Max length: **100**
        + `description` (string) - Short text description for the gifts list - Max length: **255**
        + `permalink` (string) - URL to gifts list page - Max length: **255** - Format: **uri**
        + `event_date` (string) - Date and time of the event in ISO 8601 standard representation - Format: **date-time**
        + `valid_thru` (string) - Validity of the list, until this date the gifts can be bought - Format: **date-time**
        + `authors` (array) - Authors of the list, if it is a wedding list, the names of the bride and groom - Max elements: **10**
            + (string) - Author name
        + `notification_email` (string) - Email address to be notified after gift purchase - Max length: **200** - Format: **email**
        + `contact` (string) - Email address or phone number to contact list owners - Max length: **200**
    + `last_visited_products` (array) - Last products visited by the customer - Max elements: **20**
        + (string) - Product ID
    + `last_searched_terms` (array) - Last terms searched on shop by the customer - Max elements: **20**
        + (string) - Term
    + `products_purchased` (array) - Items purchased with this account, on all saved (not necessarily paid) orders - Max elements: **3000**
        + (string) - Product ID
    + `discount` (object) - Default discount exclusively for this customer
        + `apply_at`: subtotal (enum) - In which value the discount will be applied at checkout
            + `total` (string)
            + `subtotal` (string)
            + `freight` (string)
        + `type`: percentage (enum) - Discount type
            + `percentage` (string)
            + `fixed` (string)
        + `value` (number, required) - Discount value, percentage or fixed - Mininum: **-99999999** - Maximum: **99999999** - Max precision: **0.0001**
    + `tax_exempt`: true (boolean) - Whether the customer should be charged taxes when placing orders
    + `currency_id`: BRL (string) - Default currency for the user, designator according to ISO 4217 (3 uppercase letters) - RegEx pattern: **`^[A-Z]{3}$`**
    + `currency_symbol`: R$ (string) - Graphic symbol used as a shorthand for currency's name - Max length: **20**
    + `orders_count` (number) - Total number of orders completed by this customer
    + `orders_total_value` (number) - The total amount in orders completed by this customer - Mininum: **0** - Maximum: **999999999999** - Max precision: **0.00001**
    + `loyalty_points` (object) - Loyalty points programs, `program_id` as property name - Max properties: **100**
        + `^[a-z0-9_]{2,30}$` (object) - Loyalty points program object, specify how many points the customer have
            + `name` (string) - The name of the loyalty points program - Max length: **50**
            + `accumulated_points` (number, required) - Number of accumulated loyalty points - Mininum: **0** - Maximum: **999999999** - Max precision: **0.00001**
    + `affiliate_code` (string) - Code to identify the affiliate that referred the customer - Max length: **200**
    + `total_spent` (number) - The total amount of money that this customer has spent at the store - Mininum: **0** - Maximum: **999999999999** - Max precision: **0.00001**
    + `total_cancelled` (number) - The total amount in cancelled orders - Mininum: **0** - Maximum: **999999999999** - Max precision: **0.00001**
    + `orders` (array) - List of customer orders - Max elements: **1000**
        + (object) - Registered order
            + `_id` (string, required) - Order ID - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `created_at` (string) - When order was saved, date and time in ISO 8601 standard representation - Format: **date-time**
            + `number` (number) - Auto incremented order number
            + `currency_id`: BRL (string) - Designator of currency according to ISO 4217 (3 uppercase letters) - RegEx pattern: **`^[A-Z]{3}$`**
            + `currency_symbol`: R$ (string) - Graphic symbol used as a shorthand for currency's name - Max length: **20**
            + `amount` (object) - Object with sums of values
                + `total` (number, required) - Order total amount - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `subtotal` (number) - The sum of all items prices - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `freight` (number) - Order freight cost - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `discount` (number) - Applied discount value - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `tax` (number) - The sum of all the taxes applied to the order - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
                + `extra` (number) - Sum of optional extra costs applied - Mininum: **0** - Maximum: **9999999999** - Max precision: **0.00001**
            + `payment_method_label` (string) - Name or summary of order payment method(s) - Max length: **100**
            + `shipping_method_label` (string) - Name of order shipping method(s) - Max length: **100**
    + `metafields` (array) - List of custom attributes - Max elements: **100**
        + (object) - Custom attribute object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `namespace` (string) - String to help distinguish who (or which app) created and can use the metafield - Max length: **30**
            + `field` (string) - Field name - Max length: **50**
            + `value` (string, required) - Custom property value - Max length: **255**
    + `hidden_metafields` (array) - List of custom attributes - Max elements: **100**
        + (object) - Custom attribute object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `namespace` (string) - String to help distinguish who (or which app) created and can use the metafield - Max length: **30**
            + `field` (string) - Field name - Max length: **50**
            + `value` (string, required) - Custom property value - Max length: **255**
    + `flags` (array) - Flags to associate additional info - Max elements: **10**
        + (string) - Flag title
    + `notes` (string) - Optional notes with additional info about this customer - Max length: **255**
    + `staff_notes` (string) - Description and notes about this customer, available only for shop administrators - Max length: **255**

#### JSON Schema [GET]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Customers",
                "description": "Customer object model",
                "type": "object",
                "required": [
                    "main_email",
                    "display_name"
                ],
                "additionalProperties": false,
                "properties": {
                    "state": {
                        "type": "string",
                        "enum": [
                            "invited",
                            "registered",
                            "declined"
                        ],
                        "default": "registered",
                        "description": "The state of registration, if completed, invited and waiting, or declined by customer"
                    },
                    "enabled": {
                        "type": "boolean",
                        "default": true,
                        "description": "Whether customer account is enabled to make orders"
                    },
                    "login": {
                        "type": "boolean",
                        "default": true,
                        "description": "Whether the customer can sign in to the store with this account"
                    },
                    "status": {
                        "type": "string",
                        "maxLength": 50,
                        "description": "Status defined by seller, such as active or blocked"
                    },
                    "referral": {
                        "type": "string",
                        "pattern": "^[a-f0-9]{24}$",
                        "description": "ID of customer who invited this new customer, if he was invited by another account"
                    },
                    "utm": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "source": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Parameter \"utm_source\", the referrer: (e.g. google, newsletter)"
                            },
                            "medium": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Parameter \"utm_medium\", the marketing medium: (e.g. cpc, banner, email)"
                            },
                            "campaign": {
                                "type": "string",
                                "maxLength": 200,
                                "description": "Parameter \"utm_campaign\", the product, promo code, or slogan (e.g. spring_sale)"
                            },
                            "term": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Parameter \"utm_term\", identifies the paid keywords"
                            },
                            "content": {
                                "type": "string",
                                "maxLength": 255,
                                "description": "Parameter \"utm_content\", used to differentiate ads"
                            }
                        },
                        "description": "UTM campaign HTTP parameters associated with this customer's first access"
                    },
                    "oauth_providers": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "provider",
                                "user_id"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "provider": {
                                    "type": "string",
                                    "maxLength": 30,
                                    "description": "The provider with which the user authenticated, eg.: facebook"
                                },
                                "user_id": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Unique ID for the user generated by the service provider"
                                }
                            },
                            "description": "Identifiers to authorize user login"
                        },
                        "description": "Providers for OAuth authentication"
                    },
                    "locale": {
                        "type": "string",
                        "pattern": "^[a-z]{2}(_[a-z]{2})?$",
                        "description": "Customer language two letters code, sometimes with region, eg.: pt_br, fr, en_us"
                    },
                    "main_email": {
                        "type": "string",
                        "maxLength": 200,
                        "format": "email",
                        "description": "Customer main email address"
                    },
                    "emails": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "address"
                            ],
                            "properties": {
                                "address": {
                                    "type": "string",
                                    "maxLength": 200,
                                    "format": "email",
                                    "description": "The actual email address"
                                },
                                "type": {
                                    "type": "string",
                                    "enum": [
                                        "home",
                                        "personal",
                                        "work",
                                        "other"
                                    ],
                                    "description": "The type of email"
                                },
                                "verified": {
                                    "type": "boolean",
                                    "default": false,
                                    "description": "States whether or not the email address has been verified"
                                }
                            },
                            "description": "Email object"
                        },
                        "description": "List of customer email addresses"
                    },
                    "accepts_marketing": {
                        "type": "boolean",
                        "default": false,
                        "description": "Indicates whether customer would like to receive email updates from the shop"
                    },
                    "display_name": {
                        "type": "string",
                        "maxLength": 50,
                        "description": "The name of this Customer, suitable for display"
                    },
                    "name": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "family_name": {
                                "type": "string",
                                "maxLength": 70,
                                "description": "The family name of this user, or \"last name\""
                            },
                            "given_name": {
                                "type": "string",
                                "maxLength": 70,
                                "description": "The \"first name\" of this user"
                            },
                            "middle_name": {
                                "type": "string",
                                "maxLength": 255,
                                "description": "The middle name(s) of this user"
                            }
                        },
                        "description": "Customer name object"
                    },
                    "birth_date": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "day": {
                                "type": "integer",
                                "min": 1,
                                "max": 31,
                                "description": "Day of birth"
                            },
                            "month": {
                                "type": "integer",
                                "min": 1,
                                "max": 12,
                                "description": "Number of month of birth"
                            },
                            "year": {
                                "type": "integer",
                                "min": 1800,
                                "max": 2200,
                                "description": "Year of birth"
                            }
                        },
                        "description": "Date of customer birth"
                    },
                    "gender": {
                        "type": "string",
                        "enum": [
                            "f",
                            "m",
                            "x"
                        ],
                        "description": "Customer gender, female, male or third gender (X)"
                    },
                    "photos": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 20,
                        "items": {
                            "type": "string",
                            "maxLength": 255,
                            "description": "Image URL"
                        },
                        "description": "User profile pictures"
                    },
                    "phones": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "number"
                            ],
                            "properties": {
                                "country_code": {
                                    "type": "integer",
                                    "min": 1,
                                    "max": 999,
                                    "description": "Country calling code (without +), defined by standards E.123 and E.164"
                                },
                                "number": {
                                    "type": "string",
                                    "maxLength": 19,
                                    "pattern": "^[0-9]+$",
                                    "description": "The actual phone number, digits only"
                                },
                                "type": {
                                    "type": "string",
                                    "enum": [
                                        "home",
                                        "personal",
                                        "work",
                                        "other"
                                    ],
                                    "description": "The type of phone"
                                }
                            },
                            "description": "Phone object"
                        },
                        "description": "List of customer phone numbers"
                    },
                    "registry_type": {
                        "type": "string",
                        "enum": [
                            "p",
                            "j"
                        ],
                        "description": "Physical or juridical (company) person"
                    },
                    "doc_country": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 2,
                        "pattern": "^[A-Z]+$",
                        "description": "Country of document origin, an ISO 3166-2 code"
                    },
                    "doc_number": {
                        "type": "string",
                        "maxLength": 19,
                        "pattern": "^[0-9]+$",
                        "description": "Responsible person or organization document number (only numbers)"
                    },
                    "inscription_type": {
                        "type": "string",
                        "enum": [
                            "State",
                            "Municipal"
                        ],
                        "description": "Municipal or state registration if exists"
                    },
                    "inscription_number": {
                        "type": "string",
                        "maxLength": 50,
                        "description": "Municipal or state registration number (with characters) if exists"
                    },
                    "corporate_name": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Registered company name or responsible fullname"
                    },
                    "addresses": {
                        "type": "array",
                        "maxItems": 40,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "zip"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "zip": {
                                    "type": "string",
                                    "maxLength": 30,
                                    "description": "ZIP (CEP, postal...) code"
                                },
                                "street": {
                                    "type": "string",
                                    "maxLength": 200,
                                    "description": "Street or public place name"
                                },
                                "number": {
                                    "type": "integer",
                                    "min": 1,
                                    "max": 9999999,
                                    "description": "House or building street number"
                                },
                                "complement": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Address complement or second line, such as apartment number"
                                },
                                "borough": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Borough name"
                                },
                                "near_to": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Some optional other reference for this address"
                                },
                                "line_address": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Full in line mailing address, should include street, number and borough"
                                },
                                "city": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "City name"
                                },
                                "country": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Country name"
                                },
                                "country_code": {
                                    "type": "string",
                                    "minLength": 2,
                                    "maxLength": 2,
                                    "pattern": "^[A-Z]+$",
                                    "description": "An ISO 3166-2 country code"
                                },
                                "province": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Province or state name"
                                },
                                "province_code": {
                                    "type": "string",
                                    "minLength": 2,
                                    "maxLength": 2,
                                    "pattern": "^[A-Z]+$",
                                    "description": "The two-letter code for the province or state"
                                },
                                "name": {
                                    "type": "string",
                                    "maxLength": 70,
                                    "description": "The name of recipient, generally is the customer's name"
                                },
                                "last_name": {
                                    "type": "string",
                                    "maxLength": 70,
                                    "description": "The recipient's last name"
                                },
                                "phone": {
                                    "type": "object",
                                    "additionalProperties": false,
                                    "required": [
                                        "number"
                                    ],
                                    "properties": {
                                        "country_code": {
                                            "type": "integer",
                                            "min": 1,
                                            "max": 999,
                                            "description": "Country calling code (without +), defined by standards E.123 and E.164"
                                        },
                                        "number": {
                                            "type": "string",
                                            "maxLength": 19,
                                            "pattern": "^[0-9]+$",
                                            "description": "The actual phone number, digits only"
                                        }
                                    },
                                    "description": "Customer phone number for this mailing address"
                                },
                                "default": {
                                    "type": "boolean",
                                    "default": false,
                                    "description": "Indicates whether this address is the default address for the customer"
                                }
                            },
                            "description": "Address object"
                        },
                        "description": "List of customer addresses"
                    },
                    "seller_recommendations": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "products"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "title": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Collection title"
                                },
                                "products": {
                                    "type": "array",
                                    "uniqueItems": true,
                                    "maxItems": 100,
                                    "items": {
                                        "type": "string",
                                        "pattern": "^[a-f0-9]{24}$",
                                        "description": "Product ID"
                                    },
                                    "description": "List of products"
                                },
                                "tag": {
                                    "type": "string",
                                    "maxLength": 20,
                                    "pattern": "^[a-z0-9_]+$",
                                    "description": "Tag to identify object, use only lowercase letters, digits and underscore"
                                }
                            },
                            "description": "Collection object"
                        },
                        "description": "Lists (collections) of products recommended by seller to this customer"
                    },
                    "lists": {
                        "type": "array",
                        "maxItems": 20,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "products"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "title": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Collection title"
                                },
                                "products": {
                                    "type": "array",
                                    "uniqueItems": true,
                                    "maxItems": 300,
                                    "items": {
                                        "type": "string",
                                        "pattern": "^[a-f0-9]{24}$",
                                        "description": "Product ID"
                                    },
                                    "description": "List of products"
                                },
                                "tag": {
                                    "type": "string",
                                    "maxLength": 20,
                                    "pattern": "^[a-z0-9_]+$",
                                    "description": "Tag to identify object, use only lowercase letters, digits and underscore"
                                }
                            },
                            "description": "Collection object"
                        },
                        "description": "Lists (collections) of products selected by the customer"
                    },
                    "ai_recommendations": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 100,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Product ID"
                        },
                        "description": "Products recommended by artificial intelligence (machine learning)"
                    },
                    "favorites": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 3000,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Product ID"
                        },
                        "description": "Products marked as favorites"
                    },
                    "gifts_list": {
                        "type": "array",
                        "maxItems": 3000,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Product ID"
                                },
                                "waiting": {
                                    "type": "boolean",
                                    "default": true,
                                    "description": "Whether the gift is waiting to buyer or has already been purchased"
                                },
                                "flags": {
                                    "type": "array",
                                    "uniqueItems": true,
                                    "maxItems": 10,
                                    "items": {
                                        "type": "string",
                                        "maxLength": 20,
                                        "description": "Flag title"
                                    },
                                    "description": "Flags to associate additional info"
                                }
                            },
                            "description": "Collection object"
                        },
                        "description": "Products added to customer's gift list"
                    },
                    "gifts_list_info": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "title": {
                                "type": "string",
                                "maxLength": 100,
                                "description": "Title for the gifts list, generally defined by the customer"
                            },
                            "description": {
                                "type": "string",
                                "maxLength": 255,
                                "description": "Short text description for the gifts list"
                            },
                            "permalink": {
                                "type": "string",
                                "maxLength": 255,
                                "format": "uri",
                                "description": "URL to gifts list page"
                            },
                            "event_date": {
                                "type": "string",
                                "format": "date-time",
                                "description": "Date and time of the event in ISO 8601 standard representation"
                            },
                            "valid_thru": {
                                "type": "string",
                                "format": "date-time",
                                "description": "Validity of the list, until this date the gifts can be bought"
                            },
                            "authors": {
                                "type": "array",
                                "uniqueItems": true,
                                "maxItems": 10,
                                "items": {
                                    "type": "string",
                                    "maxLength": 70,
                                    "description": "Author name"
                                },
                                "description": "Authors of the list, if it is a wedding list, the names of the bride and groom"
                            },
                            "notification_email": {
                                "type": "string",
                                "maxLength": 200,
                                "format": "email",
                                "description": "Email address to be notified after gift purchase"
                            },
                            "contact": {
                                "type": "string",
                                "maxLength": 200,
                                "description": "Email address or phone number to contact list owners"
                            }
                        },
                        "description": "Informations about this customer gifts list"
                    },
                    "last_visited_products": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 20,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Product ID"
                        },
                        "description": "Last products visited by the customer"
                    },
                    "last_searched_terms": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 20,
                        "items": {
                            "type": "string",
                            "maxLength": 50,
                            "description": "Term"
                        },
                        "description": "Last terms searched on shop by the customer"
                    },
                    "products_purchased": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 3000,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{24}$",
                            "description": "Product ID"
                        },
                        "description": "Items purchased with this account, on all saved (not necessarily paid) orders"
                    },
                    "discount": {
                        "type": "object",
                        "required": [
                            "value"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "apply_at": {
                                "type": "string",
                                "enum": [
                                    "total",
                                    "subtotal",
                                    "freight"
                                ],
                                "default": "subtotal",
                                "description": "In which value the discount will be applied at checkout"
                            },
                            "type": {
                                "type": "string",
                                "enum": [
                                    "percentage",
                                    "fixed"
                                ],
                                "default": "percentage",
                                "description": "Discount type"
                            },
                            "value": {
                                "type": "number",
                                "multipleOf": 0.0001,
                                "minimum": -99999999,
                                "maximum": 99999999,
                                "description": "Discount value, percentage or fixed"
                            }
                        },
                        "description": "Default discount exclusively for this customer"
                    },
                    "tax_exempt": {
                        "type": "boolean",
                        "default": true,
                        "description": "Whether the customer should be charged taxes when placing orders"
                    },
                    "currency_id": {
                        "type": "string",
                        "pattern": "^[A-Z]{3}$",
                        "default": "BRL",
                        "description": "Default currency for the user, designator according to ISO 4217 (3 uppercase letters)"
                    },
                    "currency_symbol": {
                        "type": "string",
                        "maxLength": 20,
                        "default": "R$",
                        "description": "Graphic symbol used as a shorthand for currency's name"
                    },
                    "orders_count": {
                        "type": "integer",
                        "min": 0,
                        "max": 9999999,
                        "description": "Total number of orders completed by this customer"
                    },
                    "orders_total_value": {
                        "type": "number",
                        "multipleOf": 0.00001,
                        "minimum": 0,
                        "maximum": 999999999999,
                        "description": "The total amount in orders completed by this customer"
                    },
                    "loyalty_points": {
                        "type": "object",
                        "additionalProperties": false,
                        "maxProperties": 100,
                        "patternProperties": {
                            "^[a-z0-9_]{2,30}$": {
                                "type": "object",
                                "required": [
                                    "accumulated_points"
                                ],
                                "additionalProperties": false,
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "maxLength": 50,
                                        "description": "The name of the loyalty points program"
                                    },
                                    "accumulated_points": {
                                        "type": "number",
                                        "multipleOf": 0.00001,
                                        "minimum": 0,
                                        "maximum": 999999999,
                                        "description": "Number of accumulated loyalty points"
                                    }
                                },
                                "description": "Loyalty points program object, specify how many points the customer have"
                            }
                        },
                        "description": "Loyalty points programs, program_id as property name"
                    },
                    "affiliate_code": {
                        "type": "string",
                        "maxLength": 200,
                        "description": "Code to identify the affiliate that referred the customer"
                    },
                    "total_spent": {
                        "type": "number",
                        "multipleOf": 0.00001,
                        "minimum": 0,
                        "maximum": 999999999999,
                        "description": "The total amount of money that this customer has spent at the store"
                    },
                    "total_cancelled": {
                        "type": "number",
                        "multipleOf": 0.00001,
                        "minimum": 0,
                        "maximum": 999999999999,
                        "description": "The total amount in cancelled orders"
                    },
                    "orders": {
                        "type": "array",
                        "maxItems": 1000,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Order ID"
                                },
                                "created_at": {
                                    "type": "string",
                                    "format": "date-time",
                                    "description": "When order was saved, date and time in ISO 8601 standard representation"
                                },
                                "number": {
                                    "type": "integer",
                                    "min": 1,
                                    "max": 999999999,
                                    "description": "Auto incremented order number"
                                },
                                "currency_id": {
                                    "type": "string",
                                    "pattern": "^[A-Z]{3}$",
                                    "default": "BRL",
                                    "description": "Designator of currency according to ISO 4217 (3 uppercase letters)"
                                },
                                "currency_symbol": {
                                    "type": "string",
                                    "maxLength": 20,
                                    "default": "R$",
                                    "description": "Graphic symbol used as a shorthand for currency's name"
                                },
                                "amount": {
                                    "type": "object",
                                    "additionalProperties": false,
                                    "required": [
                                        "total"
                                    ],
                                    "properties": {
                                        "total": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "Order total amount"
                                        },
                                        "subtotal": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "The sum of all items prices"
                                        },
                                        "freight": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "Order freight cost"
                                        },
                                        "discount": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "Applied discount value"
                                        },
                                        "tax": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "The sum of all the taxes applied to the order"
                                        },
                                        "extra": {
                                            "type": "number",
                                            "multipleOf": 0.00001,
                                            "minimum": 0,
                                            "maximum": 9999999999,
                                            "description": "Sum of optional extra costs applied"
                                        }
                                    },
                                    "description": "Object with sums of values"
                                },
                                "payment_method_label": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Name or summary of order payment method(s)"
                                },
                                "shipping_method_label": {
                                    "type": "string",
                                    "maxLength": 100,
                                    "description": "Name of order shipping method(s)"
                                }
                            },
                            "description": "Registered order"
                        },
                        "description": "List of customer orders"
                    },
                    "metafields": {
                        "type": "array",
                        "maxItems": 100,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "value"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "namespace": {
                                    "type": "string",
                                    "maxLength": 30,
                                    "description": "String to help distinguish who (or which app) created and can use the metafield"
                                },
                                "field": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Field name"
                                },
                                "value": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Custom property value"
                                }
                            },
                            "description": "Custom attribute object"
                        },
                        "description": "List of custom attributes"
                    },
                    "hidden_metafields": {
                        "type": "array",
                        "maxItems": 100,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "_id",
                                "value"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Unique ID (ObjectID)"
                                },
                                "namespace": {
                                    "type": "string",
                                    "maxLength": 30,
                                    "description": "String to help distinguish who (or which app) created and can use the metafield"
                                },
                                "field": {
                                    "type": "string",
                                    "maxLength": 50,
                                    "description": "Field name"
                                },
                                "value": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "description": "Custom property value"
                                }
                            },
                            "description": "Custom attribute object"
                        },
                        "description": "List of custom attributes"
                    },
                    "flags": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 10,
                        "items": {
                            "type": "string",
                            "maxLength": 20,
                            "description": "Flag title"
                        },
                        "description": "Flags to associate additional info"
                    },
                    "notes": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Optional notes with additional info about this customer"
                    },
                    "staff_notes": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Description and notes about this customer, available only for shop administrators"
                    }
                }
            }

### All Customers [/customers.json{?limit,offset,sort,fields}]

*/customers.json?limit&offset&sort&fields\&[field]*

> Authentication<br>_GET_: **required**

Use [default URL parameters](#introduction/overview/url-params) (metadata)
for pagination and ordering, you can use any other parameter to query
by particular object properties

#### List All Store Customers [GET /customers.json]

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "state",
                  "enabled",
                  "login",
                  "status",
                  "main_email",
                  "display_name"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "3c1000000000000000000001",
                  "state": "registered",
                  "enabled": true,
                  "login": true,
                  "status": "active",
                  "main_email": "123@mail.com",
                  "display_name": "Fulano"
                },
                {
                  "_id": "3c1000000000000000000002",
                  "state": "registered",
                  "enabled": true,
                  "login": true,
                  "status": "active",
                  "main_email": "johndoe@mail.com",
                  "display_name": "John"
                },
                {
                  "_id": "3c1000000000000000000003",
                  "state": "registered",
                  "enabled": true,
                  "login": true,
                  "main_email": "mail@sample.ex",
                  "display_name": "Jane"
                },
                {
                  "_id": "3c1000000000000000000004",
                  "state": "registered",
                  "enabled": false,
                  "login": false,
                  "status": "untrusted",
                  "main_email": "456@mail.com",
                  "display_name": "Richard"
                },
                {
                  "_id": "3c1000000000000000000005",
                  "state": "registered",
                  "enabled": true,
                  "login": true,
                  "status": "star",
                  "main_email": "janerue@mail.ex",
                  "display_name": "Jane Rue"
                },
                {
                  "_id": "3c1000000000000000000006",
                  "state": "registered",
                  "enabled": true,
                  "login": false,
                  "status": "buy_only",
                  "main_email": "abc@mail.com",
                  "display_name": "Name"
                }
              ]
            }

#### Pagination And Ordering [GET]

+ Parameters
    + limit: 2 (number, optional) - Max number of objects to return
    + offset: 4 (number, optional) - First entry to return
    + sort: `gender` (string, optional) - Rules to order resultant objects
    + fields: `emails,name,gender` (string, optional) - Object properties to return

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 2,
                "offset": 4,
                "sort": [
                  {
                    "field": "gender",
                    "order": 1
                  }
                ],
                "fields": [
                  "emails",
                  "name",
                  "gender"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "3c1000000000000000000004",
                  "emails": [
                    {
                      "address": "456@mail.com",
                      "type": "personal",
                      "verified": true
                    },
                    {
                      "address": "richarddoe@inc.sample",
                      "type": "work",
                      "verified": false
                    }
                  ],
                  "name": {
                    "family_name": "Doe",
                    "given_name": "Richard"
                  },
                  "gender": "m"
                },
                {
                  "_id": "3c1000000000000000000006",
                  "emails": [
                    {
                      "address": "abc@mail.com",
                      "type": "personal",
                      "verified": true
                    }
                  ],
                  "name": {
                    "family_name": "Last",
                    "given_name": "Name",
                    "middle_name": "Middle"
                  },
                  "gender": "x"
                }
              ]
            }

#### Find Customers [GET /customers.json{?main_email}]

+ Parameters
    + `main_email`: `janerue@mail.ex` (string, optional) - Object property to query

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "state",
                  "enabled",
                  "login",
                  "status",
                  "main_email",
                  "display_name"
                ],
                "query": {
                  "main_email": "janerue@mail.ex"
                }
              },
              "result": [
                {
                  "_id": "3c1000000000000000000005",
                  "state": "registered",
                  "enabled": true,
                  "login": true,
                  "status": "star",
                  "main_email": "janerue@mail.ex",
                  "display_name": "Jane Rue"
                }
              ]
            }

### New Customer [/customers.json]

*/customers.json*

> Authentication<br>_POST_: **required**

Request body must obey the specifications of
[this model](#reference/customers/customer-object)

The properties `orders_count`, `orders_total_value`,
`total_spent`, `total_cancelled` and `orders`
will be filled automatically (except if disabled by merchant),
but you can also preset these values if you want to

#### Create New Customer [POST]

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "oauth_providers": [
                {
                  "_id": "3c2a00000000000000000003",
                  "provider": "facebook",
                  "user_id": "1234567890"
                }
              ],
              "main_email": "mail@sample.ex",
              "emails": [
                {
                  "address": "mail@sample.ex",
                  "type": "personal",
                  "verified": true
                },
                {
                  "address": "janedue@inc.sample",
                  "type": "work",
                  "verified": false
                }
              ],
              "accepts_marketing": true,
              "display_name": "Jane",
              "name": {
                "family_name": "Due",
                "given_name": "Jane"
              },
              "gender": "f",
              "phones": [
                {
                  "country_code": 55,
                  "number": "31999889988",
                  "type": "personal"
                },
                {
                  "country_code": 55,
                  "number": "3133443344",
                  "type": "home"
                }
              ],
              "registry_type": "p",
              "doc_country": "BR",
              "doc_number": "11111111111",
              "addresses": [
                {
                  "_id": "4d2b00000000000000000003",
                  "zip": "30111222",
                  "street": "Rua Augusta",
                  "number": 92200,
                  "complement": "Apto. 200",
                  "borough": "Jardins",
                  "near_to": "Supermercado Exemplifica",
                  "line_address": "Rua Augusta 922200 Apto. 200, Jardins, Belo Horizonte, MG",
                  "city": "Belo Horizonte",
                  "country": "Brasil",
                  "country_code": "BR",
                  "province": "Minas Gerais",
                  "province_code": "MG",
                  "name": "Fulano",
                  "last_name": "Beltrano",
                  "phone": {
                    "country_code": 55,
                    "number": "31999889988"
                  },
                  "default": true
                }
              ]
            }

+ Response 201 (application/json)

    + Body

            {
              "_id": "3c1000000000000000000003"
            }

### Specific Customer [/customers/{_id}.json]

*/customers/[_id].json*

> Authentication<br>_GET_: **optional**<br>_PATCH_, _PUT_, _DELETE_: **required**

In read requests, response body will follow
[this model](#reference/customers/customer-object),
requests without authentication will receive customer data without
`main_email`, `emails`, `name`, `photos`, `phones`, `doc_number`, `inscription_number`,
`corporate_name`, `addresses`, `hidden_metafields` and `staff_notes` properties

For overwriting and editing, request body must obey the same specifications,
but especially for edit requests there are no required fields

#### Read Customer [GET /customers/{customer}.json]

+ Parameters
    + customer: 3c1000000000000000000003 (string, required) - The customer ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "_id": "3c1000000000000000000003",
              "created_at": "2017-11-18T12:10:00.612Z",
              "store_id": 100,
              "state": "registered",
              "enabled": true,
              "login": true,
              "oauth_providers": [
                {
                  "_id": "3c2a00000000000000000003",
                  "provider": "facebook",
                  "user_id": "1234567890"
                }
              ],
              "accepts_marketing": true,
              "display_name": "Jane",
              "gender": "f",
              "registry_type": "p",
              "doc_country": "BR",
              "tax_exempt": true,
              "currency_id": "BRL",
              "currency_symbol": "R$"
            }

#### With Authentication [GET]

+ Parameters
    + _id: 3c1000000000000000000003 (string, required) - The customer ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "_id": "3c1000000000000000000003",
              "created_at": "2017-11-18T12:10:00.612Z",
              "store_id": 100,
              "state": "registered",
              "enabled": true,
              "login": true,
              "oauth_providers": [
                {
                  "_id": "3c2a00000000000000000003",
                  "provider": "facebook",
                  "user_id": "1234567890"
                }
              ],
              "main_email": "mail@sample.ex",
              "emails": [
                {
                  "address": "mail@sample.ex",
                  "type": "personal",
                  "verified": true
                },
                {
                  "address": "janedue@inc.sample",
                  "type": "work",
                  "verified": false
                }
              ],
              "accepts_marketing": true,
              "display_name": "Jane",
              "name": {
                "family_name": "Due",
                "given_name": "Jane"
              },
              "gender": "f",
              "phones": [
                {
                  "country_code": 55,
                  "number": "31999889988",
                  "type": "personal"
                },
                {
                  "country_code": 55,
                  "number": "3133443344",
                  "type": "home"
                }
              ],
              "registry_type": "p",
              "doc_country": "BR",
              "doc_number": "11111111111",
              "addresses": [
                {
                  "_id": "4d2b00000000000000000003",
                  "zip": "30111222",
                  "street": "Rua Augusta",
                  "number": 92200,
                  "complement": "Apto. 200",
                  "borough": "Jardins",
                  "near_to": "Supermercado Exemplifica",
                  "line_address": "Rua Augusta 922200 Apto. 200, Jardins, Belo Horizonte, MG",
                  "city": "Belo Horizonte",
                  "country": "Brasil",
                  "country_code": "BR",
                  "province": "Minas Gerais",
                  "province_code": "MG",
                  "name": "Fulano",
                  "last_name": "Beltrano",
                  "phone": {
                    "country_code": 55,
                    "number": "31999889988"
                  },
                  "default": true
                }
              ],
              "tax_exempt": true,
              "currency_id": "BRL",
              "currency_symbol": "R$"
            }

#### Edit Customer [PATCH]

+ Parameters
    + _id: 3c1000000000000000000003 (string, required) - The customer ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "status": "active",
              "staff_notes": "This customer is a good person"
            }

+ Response 204

#### Overwrite Customer [PUT]

+ Parameters
    + _id: 3c1000000000000000000003 (string, required) - The customer ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "status": "active",
              "oauth_providers": [
                {
                  "_id": "3c2a00000000000000000003",
                  "provider": "facebook",
                  "user_id": "9999999998"
                }
              ],
              "main_email": "mail@sample.ex",
              "emails": [
                {
                  "address": "mail@sample.ex",
                  "type": "personal",
                  "verified": true
                },
                {
                  "address": "janedue@inc.sample",
                  "type": "work",
                  "verified": false
                }
              ],
              "accepts_marketing": true,
              "display_name": "Jane",
              "name": {
                "family_name": "Due",
                "given_name": "Jane",
                "middle_name": "Roe"
              },
              "gender": "f",
              "phones": [
                {
                  "country_code": 55,
                  "number": "31999889988",
                  "type": "personal"
                },
                {
                  "country_code": 55,
                  "number": "3133443344",
                  "type": "home"
                }
              ],
              "registry_type": "p",
              "doc_country": "BR",
              "doc_number": "11111111111",
              "addresses": [
                {
                  "_id": "4d2b00000000000000000003",
                  "zip": "30111222",
                  "street": "Rua Augusta",
                  "number": 92200,
                  "complement": "Apto. 200",
                  "borough": "Jardins",
                  "near_to": "Supermercado Exemplifica",
                  "line_address": "Rua Augusta 922200 Apto. 200, Jardins, Belo Horizonte, MG",
                  "city": "Belo Horizonte",
                  "country": "Brasil",
                  "country_code": "BR",
                  "province": "Minas Gerais",
                  "province_code": "MG",
                  "name": "Fulano",
                  "last_name": "Beltrano",
                  "phone": {
                    "country_code": 55,
                    "number": "31999889988"
                  },
                  "default": true
                }
              ]
            }

+ Response 204

#### Remove Customer [DELETE]

+ Parameters
    + _id: 3c1000000000000000000003 (string, required) - The customer ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 204
