+ Parameters
    + cart: 2ca000000000000000000003 (string, required) - The cart ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "product_id": "123a5432109876543210cdef",
              "quantity": 2,
              "price": 42.9
            }

+ Response 200 (application/json)

    + Body

            {
              "_id": "2ca00000000000000000e001"
            }
