+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "One of the cart items",
                "type": "object",
                "required": [
                    "product_id",
                    "quantity",
                    "price"
                ],
                "additionalProperties": false,
                "properties": {
                    "product_id": {
                        "type": "string",
                        "pattern": "^[a-f0-9]{24}$",
                        "description": "Product ID"
                    },
                    "variation_id": {
                        "type": "string",
                        "pattern": "^[a-f0-9]{24}$",
                        "description": "ID to specify the variation added to cart, if product has variations"
                    },
                    "sku": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 100,
                        "pattern": "^[A-Za-z0-9-_.]+$",
                        "description": "Product or variation unique reference code"
                    },
                    "name": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Product or variation full name, or other label for this cart item"
                    },
                    "picture": {
                        "type": "object",
                        "additionalProperties": false,
                        "patternProperties": {
                            "^small|normal|big|zoom|custom$": {
                                "type": "object",
                                "required": [
                                    "url"
                                ],
                                "additionalProperties": false,
                                "properties": {
                                    "url": {
                                        "type": "string",
                                        "maxLength": 255,
                                        "format": "uri",
                                        "description": "Image link"
                                    },
                                    "size": {
                                        "type": "string",
                                        "maxLength": 11,
                                        "pattern": "^[1-9]([0-9]+)?x[1-9]([0-9]+)?$",
                                        "description": "Image size (width x height) in px, such as 100x50 (100px width, 50px height)"
                                    },
                                    "alt": {
                                        "type": "string",
                                        "maxLength": 255,
                                        "description": "Alternative text, HTML alt tag (important for SEO)"
                                    }
                                },
                                "description": "Image size variation"
                            }
                        },
                        "description": "Product or variation picture for this cart item"
                    },
                    "customizations": {
                        "type": "array",
                        "maxItems": 100,
                        "items": {
                            "type": "object",
                            "required": [
                                "_id",
                                "option"
                            ],
                            "additionalProperties": false,
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "pattern": "^[a-f0-9]{24}$",
                                    "description": "Customization field ID"
                                },
                                "label": {
                                    "type": "string",
                                    "maxLength": 70,
                                    "description": "Title for this customization field, can be the grid title"
                                },
                                "option": {
                                    "type": "object",
                                    "required": [
                                        "text"
                                    ],
                                    "additionalProperties": false,
                                    "properties": {
                                        "option_id": {
                                            "type": "string",
                                            "pattern": "^[a-z0-9_]{2,30}$",
                                            "description": "Identify option if it was predefined (not custom value created by customer)"
                                        },
                                        "text": {
                                            "type": "string",
                                            "maxLength": 70,
                                            "description": "Option text value displayed for the client"
                                        },
                                        "colors": {
                                            "type": "array",
                                            "maxItems": 6,
                                            "items": {
                                                "type": "string",
                                                "pattern": "^#[a-f0-9]{6}$",
                                                "description": "RGB code with #"
                                            },
                                            "description": "Option color palette (if the field involves colors), starting by main color"
                                        }
                                    },
                                    "description": "Option chosen or created by customer"
                                },
                                "attachment": {
                                    "type": "string",
                                    "maxLength": 255,
                                    "format": "uri",
                                    "description": "URL of file attached by customer to this field"
                                },
                                "add_to_price": {
                                    "type": "object",
                                    "required": [
                                        "addition"
                                    ],
                                    "additionalProperties": false,
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "enum": [
                                                "percentage",
                                                "fixed"
                                            ],
                                            "default": "percentage",
                                            "description": "Type of price addition"
                                        },
                                        "addition": {
                                            "type": "number",
                                            "multipleOf": 0.0001,
                                            "minimum": -99999999,
                                            "maximum": 99999999,
                                            "description": "Additional value, could be negative"
                                        }
                                    },
                                    "description": "Price alteration due to this customization"
                                }
                            },
                            "description": "Customization field"
                        },
                        "description": "Item customization fields"
                    },
                    "gift_wrap": {
                        "type": "object",
                        "required": [
                            "label"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "tag": {
                                "type": "string",
                                "maxLength": 20,
                                "pattern": "^[a-z0-9_]+$",
                                "description": "Tag to identify object, use only lowercase letters, digits and underscore"
                            },
                            "label": {
                                "type": "string",
                                "maxLength": 70,
                                "description": "Title describing this gift wrap"
                            },
                            "add_to_price": {
                                "type": "number",
                                "multipleOf": 0.0001,
                                "minimum": 0,
                                "maximum": 99999999,
                                "description": "Additional value due to this gift wrap"
                            }
                        },
                        "description": "Gift wrap chosen by customer"
                    },
                    "quantity": {
                        "type": "number",
                        "multipleOf": 0.0001,
                        "minimum": 0,
                        "maximum": 9999999,
                        "description": "Item quantity in cart"
                    },
                    "min_quantity": {
                        "type": "number",
                        "multipleOf": 0.0001,
                        "minimum": 0,
                        "maximum": 999999,
                        "description": "Minimum item quantity for this cart"
                    },
                    "max_quantity": {
                        "type": "number",
                        "multipleOf": 0.0001,
                        "minimum": 0,
                        "maximum": 9999999,
                        "description": "Maximum item quantity for this cart"
                    },
                    "keep_item_quantity": {
                        "type": "boolean",
                        "default": false,
                        "description": "True if product quantity should not be checked, using quantity specified for this item"
                    },
                    "currency_id": {
                        "type": "string",
                        "pattern": "^[A-Z]{3}$",
                        "default": "BRL",
                        "description": "Designator of currency according to ISO 4217 (3 uppercase letters)"
                    },
                    "currency_symbol": {
                        "type": "string",
                        "maxLength": 20,
                        "default": "R$",
                        "description": "Graphic symbol used as a shorthand for currency's name"
                    },
                    "price": {
                        "type": "number",
                        "multipleOf": 0.00001,
                        "minimum": 0,
                        "maximum": 999999999,
                        "description": "Product sale price specifically for this cart"
                    },
                    "final_price": {
                        "type": "number",
                        "multipleOf": 0.00001,
                        "minimum": 0,
                        "maximum": 999999999,
                        "description": "Final item price including additions due to customizations and gift wrap"
                    },
                    "keep_item_price": {
                        "type": "boolean",
                        "default": false,
                        "description": "True if the product price should not be checked, using price specified for this item"
                    },
                    "flags": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 10,
                        "items": {
                            "type": "string",
                            "maxLength": 20,
                            "description": "Flag title"
                        },
                        "description": "Flags to associate additional info"
                    }
                }
            }
