+ Parameters
    + cart: 2ca000000000000000000003 (string, required) - The cart ID
    + _id: 2ca00000000000000000e002 (string, required) - The cart item ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "_id": "2ca00000000000000000e002",
              "product_id": "1234567890abcdef01291511",
              "variation_id": "a234567890abcdef01291511",
              "sku": "S_123456789",
              "quantity": 1,
              "price": 70
            }
