+ Attributes (object)
    + `name` (string, required) - Category full name - Max length: **255**
    + `i18n` (object) - Category name translations - Max properties: **10**
        + `^[a-z]{2}(_[a-z]{2})?$` (string) - Translated full category name - Max length: **255**
    + `subtitle` (string) - Optional subtitle intended to be used for SEO or layout purposes - Max length: **255**
    + `slug` (string) - Slug to complete page URL, starting with number or lowercase letter - Max length: **255** - RegEx pattern: **`^[a-z0-9]([a-z0-9-_./]+)?$`**
    + `permalink` (string) - Permanent URL to category page - Max length: **255** - Format: **uri**
    + `mobile_link` (string) - Optional URL specific to mobile devices - Max length: **255** - Format: **uri**
    + `short_description` (string) - Short category description in plain text - Max length: **255**
    + `body_html` (string) - Full category description, may use HTML tags - Max length: **250000**
    + `body_text` (string) - Full category description, plain text only - Max length: **250000**
    + `meta_title` (string) - Title tag for page SEO - Max length: **255**
    + `meta_description` (string) - Meta description tag for page SEO - Max length: **1000**
    + `parent` (object) - Category parent (above) of this category
        + `_id` (string) - Category ID - RegEx pattern: **`^[a-f0-9]{24}$`**
        + `name` (string, required) - Category name - Max length: **255**
        + `slug` (string) - Category page slug - Max length: **255** - RegEx pattern: **`^[a-z0-9]([a-z0-9-_./]+)?$`**
    + `childs` (array) - List of categories daughters of this category - Max elements: **200**
        + (object) - Child category
            + `_id` (string) - Category ID - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `name` (string, required) - Category name - Max length: **255**
            + `slug` (string) - Category page slug - Max length: **255** - RegEx pattern: **`^[a-z0-9]([a-z0-9-_./]+)?$`**
    + `grids` (object) - Grids for results filtering and products composition, `grid_id` as property name - Max properties: **200**
        + `^[a-z0-9_]{2,30}$` (object) - Grid properties
            + `_id` (string) - Grid object ID - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `title` (string, required) - Grid title - Max length: **70**
            + `is_filter`: false (boolean) - Grid used to results filtering (search aggregations)
    + `icon` (object) - Category icon image
        + `url` (string, required) - Image link - Max length: **255** - Format: **uri**
        + `size` (string) - Image size (width x height) in px, such as 100x50 (100px width, 50px height) - Max length: **11** - RegEx pattern: **`^[1-9]([0-9]+)?x[1-9]([0-9]+)?$`**
        + `alt` (string) - Alternative text, HTML alt tag (important for SEO) - Max length: **255**
    + `pictures` (array) - List of category images - Max elements: **50**
        + (object) - Image object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `tag` (string) - Tag to identify object, use only lowercase letters, digits and underscore - Max length: **20** - RegEx pattern: **`^[a-z0-9_]+$`**
            + `url` (string, required) - Image link - Max length: **255** - Format: **uri**
            + `size` (string) - Image size (width x height) in px, such as 100x50 (100px width, 50px height) - Max length: **11** - RegEx pattern: **`^[1-9]([0-9]+)?x[1-9]([0-9]+)?$`**
            + `alt` (string) - Alternative text, HTML alt tag (important for SEO) - Max length: **255**
    + `ml_category_id` (string) - Mercado Libre Taxonomy: https://api.mercadolibre.com/sites/MLB/categories - RegEx pattern: **`^ML[A-Z][0-9]{2,9}$`**
    + `google_product_category_id` (number) - Google Taxonomy: https://www.google.com/basepages/producttype/taxonomy-with-ids.pt-BR.txt - Mininum: **1** - Maximum: **999999999999**
    + `metafields` (array) - List of custom attributes - Max elements: **100**
        + (object) - Custom attribute object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `namespace` (string) - String to help distinguish who (or which app) created and can use the metafield - Max length: **30**
            + `field` (string) - Field name - Max length: **50**
            + `value` (string, required) - Custom property value - Max length: **255**
    + `flags` (array) - Flags to associate additional info - Max elements: **10**
        + (string) - Flag title
    + `notes` (string) - Optional notes with additional info about this category - Max length: **255**
