+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "name",
                  "slug"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "b10000000000000000001110",
                  "name": "Category 0",
                  "slug": "category-zero"
                },
                {
                  "_id": "b10000000000000000001111",
                  "name": "Category 1",
                  "slug": "category-one"
                },
                {
                  "_id": "b10000000000000000001112",
                  "name": "Category 2",
                  "slug": "category-two"
                },
                {
                  "_id": "b10000000000000000001113",
                  "name": "Category 3",
                  "slug": "category-three"
                },
                {
                  "_id": "b10000000000000000001114",
                  "name": "Category 4",
                  "slug": "category-four"
                },
                {
                  "_id": "b10000000000000000001115",
                  "name": "Category 5",
                  "slug": "category-five"
                },
                {
                  "_id": "b10000000000000000001116",
                  "name": "Category 6",
                  "slug": "category-six"
                },
                {
                  "_id": "f10000000000000000000001",
                  "name": "Polo Shirts",
                  "slug": "polo"
                }
              ]
            }
