## Group Product Customizations

`.products.customizations`

The **customizations** is a subresource of *products* resource,
use it to create, read, update and delete customization fields of a specific product by ID

### Product Field Object [/products/schema/customizations.json]

+ Attributes (object)
    + `tag` (string) - Tag to identify object, use only lowercase letters, digits and underscore - Max length: **20** - RegEx pattern: **`^[a-z0-9_]+$`**
    + `label` (string, required) - Title for this customization field, can be the grid title - Max length: **70**
    + `grid_id` (string) - If this field is related to a grid, put the `grid_id` - RegEx pattern: **`^[a-z0-9_]{2,30}$`**
    + `require`: false (boolean) - If field is required (true), customer must always choose a value
    + `options` (object) - Pre-defined options for this customization field, `option_id` as property name - Min properties: **1** - Max properties: **200**
        + `^[a-z0-9_]{2,30}$` (object) - Option object
            + `text` (string, required) - Option text value displayed for the client - Max length: **70**
            + `colors` (array) - Option color palette (if the field involves colors), starting by main color - Max elements: **4**
                + (string) - RGB code with #
            + `add_to_price` (object) - Specific price alteration if customer choose this option
                + `type`: percentage (enum) - Type of price addition
                    + percentage (string)
                    + fixed (string)
                + `addition` (number, required) - Additional value, could be negative - Mininum: **-99999999** - Maximum: **99999999** - Max precision: **0.0001**
    + `custom_value`: true (boolean) - If this field accept custom value defined by customer
    + `attachment`: false (boolean) - If this field accept customer file attachment
    + `add_to_price` (object) - Default (to all options) price alteration if customer use this field
        + `type`: percentage (enum) - Type of price addition
            + percentage (string)
            + fixed (string)
        + `addition` (number, required) - Additional value, could be negative - Mininum: **-99999999** - Maximum: **99999999** - Max precision: **0.0001**

#### JSON Schema [GET]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Customization field",
                "type": "object",
                "required": [
                    "label"
                ],
                "additionalProperties": false,
                "properties": {
                    "tag": {
                        "type": "string",
                        "maxLength": 20,
                        "pattern": "^[a-z0-9_]+$",
                        "description": "Tag to identify object, use only lowercase letters, digits and underscore"
                    },
                    "label": {
                        "type": "string",
                        "maxLength": 70,
                        "description": "Title for this customization field, can be the grid title"
                    },
                    "grid_id": {
                        "type": "string",
                        "pattern": "^[a-z0-9_]{2,30}$",
                        "description": "If this field is related to a grid, put the grid_id"
                    },
                    "require": {
                        "type": "boolean",
                        "default": false,
                        "description": "If field is required (true), customer must always choose a value"
                    },
                    "options": {
                        "type": "object",
                        "additionalProperties": false,
                        "minProperties": 1,
                        "maxProperties": 200,
                        "patternProperties": {
                            "^[a-z0-9_]{2,30}$": {
                                "type": "object",
                                "required": [
                                    "text"
                                ],
                                "additionalProperties": false,
                                "properties": {
                                    "text": {
                                        "type": "string",
                                        "maxLength": 70,
                                        "description": "Option text value displayed for the client"
                                    },
                                    "colors": {
                                        "type": "array",
                                        "maxItems": 4,
                                        "items": {
                                            "type": "string",
                                            "pattern": "^#[a-f0-9]{6}$",
                                            "description": "RGB code with #"
                                        },
                                        "description": "Option color palette (if the field involves colors), starting by main color"
                                    },
                                    "add_to_price": {
                                        "type": "object",
                                        "required": [
                                            "addition"
                                        ],
                                        "additionalProperties": false,
                                        "properties": {
                                            "type": {
                                                "type": "string",
                                                "enum": [
                                                    "percentage",
                                                    "fixed"
                                                ],
                                                "default": "percentage",
                                                "description": "Type of price addition"
                                            },
                                            "addition": {
                                                "type": "number",
                                                "multipleOf": 0.0001,
                                                "minimum": -99999999,
                                                "maximum": 99999999,
                                                "description": "Additional value, could be negative"
                                            }
                                        },
                                        "description": "Specific price alteration if customer choose this option"
                                    }
                                },
                                "description": "Option object"
                            }
                        },
                        "description": "Pre-defined options for this customization field, option_id as property name"
                    },
                    "custom_value": {
                        "type": "boolean",
                        "default": true,
                        "description": "If this field accept custom value defined by customer"
                    },
                    "attachment": {
                        "type": "boolean",
                        "default": false,
                        "description": "If this field accept customer file attachment"
                    },
                    "add_to_price": {
                        "type": "object",
                        "required": [
                            "addition"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": [
                                    "percentage",
                                    "fixed"
                                ],
                                "default": "percentage",
                                "description": "Type of price addition"
                            },
                            "addition": {
                                "type": "number",
                                "multipleOf": 0.0001,
                                "minimum": -99999999,
                                "maximum": 99999999,
                                "description": "Additional value, could be negative"
                            }
                        },
                        "description": "Default (to all options) price alteration if customer use this field"
                    }
                }
            }

### All Fields of a Product [/products/{product}/customizations.json{?limit,offset,sort,fields}]

*/products/[_id]/customizations.json?limit&offset&sort&fields\&[field]*

> Authentication<br>_GET_: **required**

Use [default URL parameters](#introduction/overview/url-params) (metadata)
for pagination and ordering, you can use any other parameter to query
by particular object properties

#### List All Product Customization Fields [GET /products/{product}/customizations.json]

+ Parameters
    + product: 1234567890abcdef01291511 (string, required) - Product ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "tag",
                  "label",
                  "grid_id",
                  "require",
                  "custom_value",
                  "attachment",
                  "add_to_price"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "a12000000000000000001110",
                  "label": "Smartphone model",
                  "grid_id": "smartphone_model",
                  "required": true,
                  "custom_value": false,
                  "attachment": false
                },
                {
                  "_id": "a12000000000000000001111",
                  "label": "Include glass film",
                  "grid_id": "glass_film",
                  "required": false,
                  "custom_value": false,
                  "attachment": false,
                  "add_to_price": {
                    "type": "fixed",
                    "addition": 10.00
                  }
                },
                {
                  "_id": "a12000000000000000001112",
                  "label": "Write your name on the cover",
                  "required": false,
                  "custom_value": true,
                  "attachment": false,
                  "add_to_price": {
                    "type": "fixed",
                    "addition": 5.99
                  }
                },
                {
                  "_id": "a12000000000000000001113",
                  "label": "Picture on the cover",
                  "required": false,
                  "custom_value": true,
                  "attachment": true,
                  "add_to_price": {
                    "type": "fixed",
                    "addition": 9.99
                  }
                }
              ]
            }

#### List Fields With Options [GET /products/{product}/customizations.json{?fields}]

+ Parameters
    + product: 1234567890abcdef01291511 (string, required) - Product ID
    + fields: label,options (string, optional) - Object properties to return

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "label",
                  "options"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "a12000000000000000001110",
                  "label": "Smartphone model",
                  "options": {
                    "iphone_x": {
                      "text": "iPhone X"
                    },
                    "galaxy_s7": {
                      "text": "Galaxy S7"
                    },
                    "k10_power": {
                      "text": "K10 Power"
                    }
                  }
                },
                {
                  "_id": "a12000000000000000001111",
                  "label": "Include glass film",
                  "options": {
                    "add_glass_film": {
                      "text": "Add glass film"
                    }
                  }
                },
                {
                  "_id": "a12000000000000000001112",
                  "label": "Write your name on the cover"
                },
                {
                  "_id": "a12000000000000000001113",
                  "label": "Picture on the cover"
                }
              ]
            }

### New Field to a Product [/products/{product}/customizations.json]

*/products/[_id]/customizations.json*

> Authentication<br>_POST_: **required**

Request body must obey the specifications of
[this model](#reference/product-customizations/product-field-object)

#### Add New Customization Field [POST]

+ Parameters
    + product: 1234567890abcdef01291511 (string, required) - Product ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Schema

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Customization field",
                "type": "object",
                "required": [
                    "label"
                ],
                "additionalProperties": false,
                "properties": {
                    "tag": {
                        "type": "string",
                        "maxLength": 20,
                        "pattern": "^[a-z0-9_]+$",
                        "description": "Tag to identify object, use only lowercase letters, digits and underscore"
                    },
                    "label": {
                        "type": "string",
                        "maxLength": 70,
                        "description": "Title for this customization field, can be the grid title"
                    },
                    "grid_id": {
                        "type": "string",
                        "pattern": "^[a-z0-9_]{2,30}$",
                        "description": "If this field is related to a grid, put the grid_id"
                    },
                    "require": {
                        "type": "boolean",
                        "default": false,
                        "description": "If field is required (true), customer must always choose a value"
                    },
                    "options": {
                        "type": "object",
                        "additionalProperties": false,
                        "minProperties": 1,
                        "maxProperties": 200,
                        "patternProperties": {
                            "^[a-z0-9_]{2,30}$": {
                                "type": "object",
                                "required": [
                                    "text"
                                ],
                                "additionalProperties": false,
                                "properties": {
                                    "text": {
                                        "type": "string",
                                        "maxLength": 70,
                                        "description": "Option text value displayed for the client"
                                    },
                                    "colors": {
                                        "type": "array",
                                        "maxItems": 4,
                                        "items": {
                                            "type": "string",
                                            "pattern": "^#[a-f0-9]{6}$",
                                            "description": "RGB code with #"
                                        },
                                        "description": "Option color palette (if the field involves colors), starting by main color"
                                    },
                                    "add_to_price": {
                                        "type": "object",
                                        "required": [
                                            "addition"
                                        ],
                                        "additionalProperties": false,
                                        "properties": {
                                            "type": {
                                                "type": "string",
                                                "enum": [
                                                    "percentage",
                                                    "fixed"
                                                ],
                                                "default": "percentage",
                                                "description": "Type of price addition"
                                            },
                                            "addition": {
                                                "type": "number",
                                                "multipleOf": 0.0001,
                                                "minimum": -99999999,
                                                "maximum": 99999999,
                                                "description": "Additional value, could be negative"
                                            }
                                        },
                                        "description": "Specific price alteration if customer choose this option"
                                    }
                                },
                                "description": "Option object"
                            }
                        },
                        "description": "Pre-defined options for this customization field, option_id as property name"
                    },
                    "custom_value": {
                        "type": "boolean",
                        "default": true,
                        "description": "If this field accept custom value defined by customer"
                    },
                    "attachment": {
                        "type": "boolean",
                        "default": false,
                        "description": "If this field accept customer file attachment"
                    },
                    "add_to_price": {
                        "type": "object",
                        "required": [
                            "addition"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": [
                                    "percentage",
                                    "fixed"
                                ],
                                "default": "percentage",
                                "description": "Type of price addition"
                            },
                            "addition": {
                                "type": "number",
                                "multipleOf": 0.0001,
                                "minimum": -99999999,
                                "maximum": 99999999,
                                "description": "Additional value, could be negative"
                            }
                        },
                        "description": "Default (to all options) price alteration if customer use this field"
                    }
                }
            }

    + Body

            {
              "label": "Include glass film",
              "options": {
                "add_glass_film": {
                  "text": "Add glass film"
                }
              },
              "custom_value": false,
              "add_to_price": {
                "type": "fixed",
                "addition": 10.00
              }
            }

+ Response 201 (application/json)

    + Body

            {
              "_id": "a12000000000000000001111"
            }

### Specific Field of a Product [/products/{product}/customizations/{_id}.json]

*/products/[_id]/customizations/[_id].json*

> Authentication<br>_GET_, _PATCH_, _DELETE_: **required**

In read requests, response body will follow
[this model](#reference/product-customizations/product-field-object)

For editing, request body must obey the same specifications,
but there are no required fields, object should have at least one valid property

#### Read Product Customization Field [GET]

+ Parameters
    + product: 1234567890abcdef01291511 (string, required) - Product ID
    + _id: a12000000000000000001110 (string, required) - Customization Field ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "_id": "a12000000000000000001110",
              "label": "Smartphone model",
              "grid_id": "smartphone_model",
              "required": true,
              "options": {
                "iphone_x": {
                  "text": "iPhone X"
                },
                "galaxy_s7": {
                  "text": "Galaxy S7"
                },
                "k10_power": {
                  "text": "K10 Power"
                }
              },
              "custom_value": false,
              "attachment": false
            }

#### Edit Customization Field [PATCH]

+ Parameters
    + product: 1234567890abcdef01291511 (string, required) - Product ID
    + _id: a12000000000000000001110 (string, required) - Customization Field ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Schema

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Customization field",
                "type": "object",
                "required": [],
                "minProperties": 1,
                "additionalProperties": false,
                "properties": {
                    "tag": {
                        "type": "string",
                        "maxLength": 20,
                        "pattern": "^[a-z0-9_]+$",
                        "description": "Tag to identify object, use only lowercase letters, digits and underscore"
                    },
                    "label": {
                        "type": "string",
                        "maxLength": 70,
                        "description": "Title for this customization field, can be the grid title"
                    },
                    "grid_id": {
                        "type": "string",
                        "pattern": "^[a-z0-9_]{2,30}$",
                        "description": "If this field is related to a grid, put the grid_id"
                    },
                    "require": {
                        "type": "boolean",
                        "default": false,
                        "description": "If field is required (true), customer must always choose a value"
                    },
                    "options": {
                        "type": "object",
                        "additionalProperties": false,
                        "minProperties": 1,
                        "maxProperties": 200,
                        "patternProperties": {
                            "^[a-z0-9_]{2,30}$": {
                                "type": "object",
                                "required": [
                                    "text"
                                ],
                                "additionalProperties": false,
                                "properties": {
                                    "text": {
                                        "type": "string",
                                        "maxLength": 70,
                                        "description": "Option text value displayed for the client"
                                    },
                                    "colors": {
                                        "type": "array",
                                        "maxItems": 4,
                                        "items": {
                                            "type": "string",
                                            "pattern": "^#[a-f0-9]{6}$",
                                            "description": "RGB code with #"
                                        },
                                        "description": "Option color palette (if the field involves colors), starting by main color"
                                    },
                                    "add_to_price": {
                                        "type": "object",
                                        "required": [
                                            "addition"
                                        ],
                                        "additionalProperties": false,
                                        "properties": {
                                            "type": {
                                                "type": "string",
                                                "enum": [
                                                    "percentage",
                                                    "fixed"
                                                ],
                                                "default": "percentage",
                                                "description": "Type of price addition"
                                            },
                                            "addition": {
                                                "type": "number",
                                                "multipleOf": 0.0001,
                                                "minimum": -99999999,
                                                "maximum": 99999999,
                                                "description": "Additional value, could be negative"
                                            }
                                        },
                                        "description": "Specific price alteration if customer choose this option"
                                    }
                                },
                                "description": "Option object"
                            }
                        },
                        "description": "Pre-defined options for this customization field, option_id as property name"
                    },
                    "custom_value": {
                        "type": "boolean",
                        "default": true,
                        "description": "If this field accept custom value defined by customer"
                    },
                    "attachment": {
                        "type": "boolean",
                        "default": false,
                        "description": "If this field accept customer file attachment"
                    },
                    "add_to_price": {
                        "type": "object",
                        "required": [
                            "addition"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": [
                                    "percentage",
                                    "fixed"
                                ],
                                "default": "percentage",
                                "description": "Type of price addition"
                            },
                            "addition": {
                                "type": "number",
                                "multipleOf": 0.0001,
                                "minimum": -99999999,
                                "maximum": 99999999,
                                "description": "Additional value, could be negative"
                            }
                        },
                        "description": "Default (to all options) price alteration if customer use this field"
                    }
                }
            }

    + Body

            {
              "custom_value": true
            }

+ Response 204

#### Remove Customization Field [DELETE]

+ Parameters
    + product: 1234567890abcdef01291511 (string, required) - Product ID
    + _id: a12000000000000000001110 (string, required) - Customization Field ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 204
