## Group Stores

`.stores`

Use the **stores** resource to read and update the
shop main informations and IDs of saved documents

### Store Object [/stores/schema.json]

+ Attributes (object)
    + `name` (string, required) - Store name - Max length: **255**
    + `description` (string) - Simple description of store - Max length: **3000**
    + `segment_id` (number, required) - ID of store main segment, get options and IDs at /segments.json - Mininum: **0** - Maximum: **65535**
    + `doc_type` (enum, required) - Responsible person or organization document type
        + `CPF` (string)
        + `CNPJ` (string)
    + `doc_number` (string, required) - Responsible person or organization document number (only numbers) - Max length: **19** - RegEx pattern: **`^[0-9]+$`**
    + `inscription_type` (enum) - Municipal or state registration if exists
        + `State` (string)
        + `Municipal` (string)
    + `inscription_number` (string) - Municipal or state registration number (with characters) if exists - Max length: **50**
    + `corporate_name` (string, required) - Registered company name or responsible fullname - Max length: **255**
    + `address` (string) - Full registered address of company - Max length: **255**
    + `phone` (string) - Financial contact phone - Max length: **19** - RegEx pattern: **`^[0-9]+$`**
    + `representant_name` (string) - Name of company representative for commercial contact - Max length: **255**
    + `representant_email` (string) - Email address of company representative - Max length: **255** - Format: **email**
    + `contact_email` (string) - Public email address for news and general contact - Max length: **255** - Format: **email**
    + `financial_email` (string, required) - Email address to receive notifications, invoices and vouchers - Max length: **255** - Format: **email**
    + `logo` (object) - Image link to shop's logo
        + `url` (string, required) - Image link - Max length: **255** - Format: **uri**
        + `size` (string) - Image size (width x height) in px, such as 100x50 (100px width, 50px height) - Max length: **11** - RegEx pattern: **`^[1-9]([0-9]+)?x[1-9]([0-9]+)?$`**
        + `alt` (string) - Alternative text, HTML alt tag (important for SEO) - Max length: **255**
    + `languages` (array) - List of available languages on store channels - Max elements: **30**
        + (string) - Language two letters code, sometimes with region, eg.: `pt_br`, fr, `en_us`
    + `oauth_providers` (object) - Providers for OAuth customer authentication in store
        + `^facebook|google|windowslive$` (object) - Social network OAuth app
            + `client_id` (string, required) - App client ID - Max length: **255**
            + `client_secret` (string, required) - App client secret - Max length: **255**

#### JSON Schema [GET]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Stores",
                "description": "Store info and resource IDs",
                "type": "object",
                "required": [
                    "name",
                    "segment_id",
                    "doc_type",
                    "doc_number",
                    "corporate_name",
                    "financial_email"
                ],
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Store name"
                    },
                    "description": {
                        "type": "string",
                        "maxLength": 3000,
                        "description": "Simple description of store"
                    },
                    "segment_id": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 65535,
                        "description": "ID of store main segment, get options and IDs at /segments.json"
                    },
                    "doc_type": {
                        "type": "string",
                        "enum": [
                            "CPF",
                            "CNPJ"
                        ],
                        "description": "Responsible person or organization document type"
                    },
                    "doc_number": {
                        "type": "string",
                        "maxLength": 19,
                        "pattern": "^[0-9]+$",
                        "description": "Responsible person or organization document number (only numbers)"
                    },
                    "inscription_type": {
                        "type": "string",
                        "enum": [
                            "State",
                            "Municipal"
                        ],
                        "description": "Municipal or state registration if exists"
                    },
                    "inscription_number": {
                        "type": "string",
                        "maxLength": 50,
                        "description": "Municipal or state registration number (with characters) if exists"
                    },
                    "corporate_name": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Registered company name or responsible fullname"
                    },
                    "address": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Full registered address of company"
                    },
                    "phone": {
                        "type": "string",
                        "maxLength": 19,
                        "pattern": "^[0-9]+$",
                        "description": "Financial contact phone"
                    },
                    "representant_name": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Name of company representative for commercial contact"
                    },
                    "representant_email": {
                        "type": "string",
                        "maxLength": 255,
                        "format": "email",
                        "description": "Email address of company representative"
                    },
                    "contact_email": {
                        "type": "string",
                        "maxLength": 255,
                        "format": "email",
                        "description": "Public email address for news and general contact"
                    },
                    "financial_email": {
                        "type": "string",
                        "maxLength": 255,
                        "format": "email",
                        "description": "Email address to receive notifications, invoices and vouchers"
                    },
                    "logo": {
                        "type": "object",
                        "required": [
                            "url"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "url": {
                                "type": "string",
                                "maxLength": 255,
                                "format": "uri",
                                "description": "Image link"
                            },
                            "size": {
                                "type": "string",
                                "maxLength": 11,
                                "pattern": "^[1-9]([0-9]+)?x[1-9]([0-9]+)?$",
                                "description": "Image size (width x height) in px, such as 100x50 (100px width, 50px height)"
                            },
                            "alt": {
                                "type": "string",
                                "maxLength": 255,
                                "description": "Alternative text, HTML alt tag (important for SEO)"
                            }
                        },
                        "description": "Image link to shop's logo"
                    },
                    "languages": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 30,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-z]{2}(_[a-z]{2})?$",
                            "description": "Language two letters code, sometimes with region, eg.: pt_br, fr, en_us"
                        },
                        "description": "List of available languages on store channels"
                    },
                    "oauth_providers": {
                        "type": "object",
                        "additionalProperties": false,
                        "patternProperties": {
                            "^facebook|google|windowslive$": {
                                "type": "object",
                                "additionalProperties": false,
                                "required": [
                                    "provider",
                                    "client_id",
                                    "client_secret"
                                ],
                                "properties": {
                                    "client_id": {
                                        "type": "string",
                                        "maxLength": 255,
                                        "description": "App client ID"
                                    },
                                    "client_secret": {
                                        "type": "string",
                                        "maxLength": 255,
                                        "description": "App client secret"
                                    }
                                },
                                "description": "Social network OAuth app"
                            }
                        },
                        "description": "Providers for OAuth customer authentication in store"
                    }
                }
            }

### Specific Store [/stores/{_id}.json]

*/stores/[_id].json*

> Authentication<br>_GET_: **none**

Response body will follow
[this model](#reference/stores/store-object), but only with public data,
returning `_id`, `store_id`, `name`, `description`, `segment_id`,
`contact_email`, `referral_id`, `partner_id`, `logo` and `languages` properties

#### Read Store [GET]

+ Parameters
    + _id: 5a674f224e0dcec2c3353d9d (string, required) - The store object ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "_id": "5a674f224e0dcec2c3353d9d",
              "store_id": 100,
              "name": "Minha Loja Online",
              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
              "segment_id": 23,
              "contact_email": "contato@sample.shop.eg",
              "logo": {
                "url": "https://sample.shop.eg/assets/logo.png",
                "size": "120x80"
              }
            }

### Your Store [/stores/me.json]

*/stores/me.json*

> Authentication<br>_GET_, _PATCH_: **required**

In read requests, response body will follow
[this model](#reference/stores/store-object)

For editing, request body must obey the same specifications,
but in this case there are no required fields

#### Read Your Store [GET]

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "_id": "5a674f224e0dcec2c3353d9d",
              "created_at": "2017-11-19T13:10:00.612Z",
              "store_id": 100,
              "resources": {
                "products": [
                  "1234567890abcdef01291510",
                  "1234567890abcdef01291511",
                  "1234567890abcdef01291512"
                ],
                "brands": [
                  "a10000000000000000001110",
                  "a10000000000000000001111",
                  "a10000000000000000001112",
                  "a10000000000000000001113",
                  "a10000000000000000001114",
                  "a10000000000000000001115",
                ],
                "categories": [
                  "b10000000000000000001110",
                  "b10000000000000000001111",
                  "b10000000000000000001112",
                  "b10000000000000000001113",
                  "b10000000000000000001114"
                ],
                "orders": [
                  "fe1000000000000000000000",
                  "fe1000000000000000000001"
                ]
              },
              "name": "Minha Loja Online",
              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
              "segment_id": 23,
              "doc_type": "CNPJ",
              "doc_number": "12345678901234",
              "corporate_name": "Minha Loja Online LTDA",
              "address": "Rua Exemplar 100, Bairro Examplar, São Paulo, SP",
              "phone": "31988887777",
              "representant_name": "Fulano Ciclano",
              "representant_email": "fulano@sample.shop.eg",
              "contact_email": "contato@sample.shop.eg",
              "financial_email": "financeiro@sample.shop.eg",
              "logo": {
                "url": "https://sample.shop.eg/assets/logo.png",
                "size": "120x80"
              }
            }

#### Edit Your Store [PATCH]

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
            }

+ Response 204
