+ Parameters
    + _id: 98d120000000000000000111 (string, required) - The procedure ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "webhooks": [
                {
                  "api": {
                    "external_api": {
                      "uri": "https://appserver.sample/stock/notification?order_id=(tr.inserted_id)"
                    }
                  },
                  "method": "GET",
                  "send_body": false
                }
              ]
            }

+ Response 204
