+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "query": {}
              },
              "result": [
                {
                  "_id": "98d120000000000000000110",
                  "title": "My procedure",
                  "short_description": "Do something after some other thing"
                },
                {
                  "_id": "98d120000000000000000111",
                  "title": "Reduce inventory after new order",
                  "short_description": "After receive order, reduce products available quantity to control stock"
                },
                {
                  "_id": "98d120000000000000000112",
                  "title": "Custom procedure name",
                  "short_description": "Lorem ipsum dolor sit amet..."
                }
              ]
            }
