+ Parameters
    + _id: a00000000000000000000000 (string, required) - The product ID

+ Response 200 (application/json)

        {
          "results": [
            {
              "columns": [
                "products.id"
              ],
              "data": [
                [
                  "a00000000000000000000011"
                ],
                [
                  "a00000000000000000000012"
                ],
                [
                  "a00000000000000000000013"
                ],
                [
                  "a00000000000000000000014"
                ],
                [
                  "a00000000000000000000015"
                ],
                [
                  "a00000000000000000000016"
                ],
                [
                  "a00000000000000000000017"
                ],
                [
                  "a00000000000000000000018"
                ],
                [
                  "a00000000000000000000019"
                ],
                [
                  "a0000000000000000000001a"
                ],
                [
                  "a0000000000000000000001b"
                ],
                [
                  "a0000000000000000000001c"
                ]
              ]
            }
          ],
          "errors": []
        }
