+ Attributes (object)
    + `username` (string, required) - Simple username for identification, only numbers and lowercase letters - Min length: **4** - Max length: **30** - RegEx pattern: **`^[0-9a-z]+$`**
    + `locale`: pt_br (string) - User language two letter code, sometimes with region, eg.: `pt_br`, fr, `en_us` - RegEx pattern: **`^[a-z]{2}(_[a-z]{2})?$`**
    + `email` (string) - User email address - Max length: **200** - Format: **email**
    + `name` (string) - User full name - Max length: **255**
    + `phone` (string) - User phone number - Max length: **19** - RegEx pattern: **`^[0-9]+$`**
    + `pass_md5_hash` (string) - MD5 hash generated with the user's password - RegEx pattern: **`^[a-f0-9]{32}$`**
    + `panel_preferences` (object) - User preferences in the admin dashboard - Max properties: **100**
        + `^[a-z0-9_]+$`: true (boolean) - Boolean option value
    + `panel_shortcuts` (object) - Keyboard shortcuts, keys separated by `+` as property name - Max properties: **100**
        + `^[a-z0-9](([+][a-z0-9])+)?$` (string) - Shortcut JS (or jQuery) action - Min length: **3** - Max length: **255**
    + `panel_random_cards`: 0 (number) - Number of random cards to show on dashboard home
    + `panel_cards` (array) - List of dashboard cards chosen by user - Max elements: **40**
        + (object) - Card object
            + `_id` (string, required) - Unique ID (ObjectID) - RegEx pattern: **`^[a-f0-9]{24}$`**
            + `card_id` (string) - Unique identifier, card name using only lowercase, numbers and underscore - RegEx pattern: **`^[a-z0-9_]{2,60}$`**
            + `title` (string) - Card title - Max length: **70**
            + `paragraph` (string) - Card text, usually a brief description - Max length: **255**
            + `custom_aggregation` (object) - Custom card calling MongoDB aggregate
                + `resource` (enum, required) - API resource
                    + `products` (string)
                    + `categories` (string)
                    + `brands` (string)
                    + `collections` (string)
                    + `grids` (string)
                    + `customers` (string)
                    + `carts` (string)
                    + `orders` (string)
                + `pipeline` (array, required) - Aggregation pipeline - Min elements: **1** - Max elements: **50**
                    + (object) - Custom aggregation pipeline step
    + `panel_dismissed_cards` (array) - List of dashboard dismissed cards, by `card_id` - Max elements: **300**
        + (string) - Unique identifier, card name using only lowercase, numbers and underscore
    + `panel_form_fields` (object) - Custom (user-selected) fields to display on dashboard forms, resource as property name - Max properties: **20**
        + `^[a-z]{4,60}s$` (array) - List of chosen resource properties (fields) - Max elements: **200**
            + (string) - Resource property name with dot notation for nested object
    + `edit_storefront`: true (boolean) - Whether the user is able to use builder and file manager to edit storefront
    + `flags` (array) - Flags to associate additional info - Max elements: **10**
        + (string) - Flag title
    + `notes` (string) - Optional notes with additional info about this user - Max length: **255**
