+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "username": "john_doe",
              "email": "email@sample.com",
              "name": "John Doe",
              "phone": "31911112222",
              "pass_md5_hash": "698dc19d489c4e4db73e28a713eab07b"
            }

+ Response 201 (application/json)

    + Body

            {
              "_id": "100000000000000000000011"
            }
