+ Parameters
    + _id: 100000000000000000000011 (string, required) - The authentication ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "email": "email@sample.com",
              "pass_md5_hash": "38851536d87701d2191990e24a7f8d4e"
            }

+ Response 204
