+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "_id": "5a6757722b66f68dbed44526",
              "created_at": "2017-11-18T12:30:00.612Z",
              "store_id": 100,
              "username": "my_username",
              "email": "myemail@mail.sample",
              "name": "My Full Name"
            }
