+ Parameters
    + _id: 9d1500000000000000001111 (string, required) - The grid ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "custom_value": true
            }

+ Response 204
