+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "title",
                  "grid_id"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "9d1500000000000000001110",
                  "title": "Custom grid",
                  "grid_id": "custom_grid"
                },
                {
                  "_id": "9d1500000000000000001111",
                  "title": "Smartphone model",
                  "grid_id": "smartphone_model"
                },
                {
                  "_id": "9d1500000000000000001112",
                  "title": "Include glass film",
                  "grid_id": "glass_film"
                },
                {
                  "_id": "9d1500000000000000001113",
                  "title": "Gender",
                  "grid_id": "gender"
                },
                {
                  "_id": "9d1500000000000000001114",
                  "title": "Shirt size",
                  "grid_id": "size"
                },
                {
                  "_id": "9d1500000000000000001115",
                  "title": "Colors",
                  "grid_id": "colors"
                }
              ]
            }
