+ Parameters
    + _id: fe1000000000000000000005 (string, required) - The order ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "code": "P05NX",
              "staff_notes": "To do..."
            }

+ Response 204
