+ Request (application/json)

    + Headers

            X-Store-ID: 100

    + Attributes (object)
        + _id: 5a6757722b66f68dbed44526 (string, required)
            User object ID, same returned from login
        + api_key: 1234567890abcdef (string, required)
            User API key, 128 bytes hexadecimal string, same returned from login

    + Body

            {
              "_id": "5a6757722b66f68dbed44526",
              "api_key": "1234567890abcdef"
            }

+ Response 200 (application/json)

        {
          "my_id": "5a6757722b66f68dbed44526",
          "access_token": "eyJhbGciOi.eyJzdWIi.AFONFh7HgQ",
          "expires": "2017-12-01T08:02:17-05:00"
        }
