+ Parameters
    + _id: 42aa00000000000000000111 (string, required) - The application ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "app_id": 1002,
              "state": "inactive",
              "title": "Products panel extension",
              "slug": "products-panel-ext",
              "paid": true,
              "version": "3.0.0",
              "type": "dashboard",
              "load_events": [
                "products"
              ],
              "script_uri": "https://sample.mycdn.com/script.min.js",
              "status": "paused"
            }

+ Response 204
