## Group Applications

`.applications`

Use the **applications** resource to create, read, update and delete apps in
a merchant's store, you can edit all application properties and also work with all
application subresources directly at this resource

### Application Object [/applications/schema.json]

+ Attributes (object)
    + `app_id` (number, required) - ID of application - Mininum: **1000** - Maximum: **16777215**
    + `state`: test (enum) - The working state of this app in the shop
        + `inactive` (string)
        + `active` (string)
        + `test` (string)
    + `title` (string, required) - App title - Max length: **70**
    + `slug` (string, required) - App unique slug, only lowercase letters, numbers and hyphen - Min length: **3** - Max length: **50** - RegEx pattern: **`^[0-9a-z-]+$`**
    + `paid`: false (boolean) - Whether this app is paid
    + `version` (string, required) - Version of the application that was installed, eg.: 1.0.0 - Min length: **5** - Max length: **8** - RegEx pattern: **`^(0|([1-9][0-9]?))[.](0|([1-9][0-9]?))[.](0|([1-9][0-9]?))$`**
    + `version_date` (string) - When app installation was updated, date and time in ISO 8601 standard representation - Format: **date-time**
    + `type` (enum, required) - Type of app
        + `dashboard` (string)
        + `storefront` (string)
        + `module_package` (string)
        + `external` (string)
    + `module` (enum) - If this app is a package of a module, specify the module
        + `al` (string)
        + `pd` (string)
        + `sc` (string)
        + `sh` (string)
        + `pa` (string)
        + `ck` (string)
        + `cf` (string)
        + `rg` (string)
        + `lg` (string)
        + `ct` (string)
        + `nw` (string)
    + `load_events` (array) - If this app is a dashboard or storefront JS, specify resources that trigger the script load - Max elements: **100**
        + (string) - Resource/Subresources/Third-level/ID
    + `script_uri` (string) - Script (JS) link - Max length: **255** - Format: **uri**
    + `github_repository` (string) - Link to GitHub repository - Max length: **255** - Format: **uri**
    + `status` (string) - Status defined by seller, such as active or waiting - Max length: **50**
    + `authentication`: false (boolean) - Whether this app needs to authenticate with API
    + `auth_callback_uri` (string) - Endpoint that receives POST back with authentication credentials, must be https - Max length: **255** - Format: **uri**
    + `auth_scope` (object) - If this app uses authentication, list the needed permissions - Min properties: **1** - Max properties: **20**
        + `^([$]?(?!app|aut|upd)([a-z]{1,60}))$` (array) - Requested resource, cannot be "applications", "authentications" or "$update"
            + (enum) - Methods to be used (HTTP verbs)
                + `all` (string)
                + `GET` (string)
                + `POST` (string)
                + `PATCH` (string)
                + `PUT` (string)
                + `DELETE` (string)
    + `flags` (array) - Flags to associate additional info - Max elements: **10**
        + (string) - Flag title
    + `notes` (string) - Optional notes with additional info about this user - Max length: **255**

#### JSON Schema [GET]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Applications",
                "description": "App object model",
                "type": "object",
                "required": [
                    "app_id",
                    "title",
                    "slug",
                    "version",
                    "type"
                ],
                "dependencies": {
                    "auth_scope": [
                        "auth_callback_uri"
                    ]
                },
                "additionalProperties": false,
                "properties": {
                    "app_id": {
                        "type": "integer",
                        "minimum": 1000,
                        "maximum": 16777215,
                        "description": "ID of application"
                    },
                    "state": {
                        "type": "string",
                        "enum": [
                            "inactive",
                            "active",
                            "test"
                        ],
                        "default": "test",
                        "description": "The working state of this app in the shop"
                    },
                    "title": {
                        "type": "string",
                        "maxLength": 70,
                        "description": "App title"
                    },
                    "slug": {
                        "type": "string",
                        "minLength": 3,
                        "maxLength": 50,
                        "pattern": "^[0-9a-z-]+$",
                        "description": "App unique slug, only lowercase letters, numbers and hyphen"
                    },
                    "paid": {
                        "type": "boolean",
                        "default": false,
                        "description": "Whether this app is paid"
                    },
                    "version": {
                        "type": "string",
                        "minLength": 5,
                        "maxLength": 8,
                        "pattern": "^(0|([1-9][0-9]?))[.](0|([1-9][0-9]?))[.](0|([1-9][0-9]?))$",
                        "description": "Version of the application that was installed, eg.: 1.0.0"
                    },
                    "version_date": {
                        "type": "string",
                        "format": "date-time",
                        "description": "When app installation was updated, date and time in ISO 8601 standard representation"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "dashboard",
                            "storefront",
                            "module_package",
                            "external"
                        ],
                        "description": "Type of app"
                    },
                    "module": {
                        "type": "string",
                        "enum": [
                            "al",
                            "pd",
                            "sc",
                            "sh",
                            "pa",
                            "ck",
                            "cf",
                            "rg",
                            "lg",
                            "ct",
                            "nw"
                        ],
                        "description": "If this app is a package of a module, specify the module"
                    },
                    "load_events": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 100,
                        "items": {
                            "type": "string",
                            "maxLength": 60,
                            "pattern": "^(([^/_][a-z0-9/_@:$+]{1,60}[^/])|[*])$",
                            "description": "Resource/Subresources/Third-level/ID"
                        },
                        "description": "If this app is a dashboard or storefront JS, specify resources that trigger the script load"
                    },
                    "script_uri": {
                        "type": "string",
                        "maxLength": 255,
                        "format": "uri",
                        "description": "Script (JS) link"
                    },
                    "github_repository": {
                        "type": "string",
                        "maxLength": 255,
                        "format": "uri",
                        "description": "Link to GitHub repository"
                    },
                    "status": {
                        "type": "string",
                        "maxLength": 50,
                        "description": "Status defined by seller, such as active or waiting"
                    },
                    "authentication": {
                        "type": "boolean",
                        "default": false,
                        "description": "Whether this app needs to authenticate with API"
                    },
                    "auth_callback_uri": {
                        "type": "string",
                        "maxLength": 255,
                        "format": "uri",
                        "pattern": "^https:",
                        "description": "Endpoint that receives POST back with authentication credentials, must be https"
                    },
                    "auth_scope": {
                        "type": "object",
                        "additionalProperties": false,
                        "minProperties": 1,
                        "maxProperties": 20,
                        "patternProperties": {
                            "^([$]?(?!app|aut|upd)([a-z]{1,60}))$": {
                                "type": "array",
                                "uniqueItems": true,
                                "items": {
                                    "type": "string",
                                    "enum": [
                                        "all",
                                        "GET",
                                        "POST",
                                        "PATCH",
                                        "PUT",
                                        "DELETE"
                                    ],
                                    "description": "Methods to be used (HTTP verbs)"
                                },
                                "description": "Requested resource, cannot be \"applications\", \"authentications\" or \"$update\""
                            }
                        },
                        "description": "If this app uses authentication, list the needed permissions"
                    },
                    "flags": {
                        "type": "array",
                        "uniqueItems": true,
                        "maxItems": 10,
                        "items": {
                            "type": "string",
                            "maxLength": 20,
                            "description": "Flag title"
                        },
                        "description": "Flags to associate additional info"
                    },
                    "notes": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Optional notes with additional info about this user"
                    }
                }
            }

### All Applications [/applications.json{?limit,offset,sort,fields}]

*/applications.json?limit&offset&sort&fields\&[field]*

> Authentication<br>_GET_: **required**

Use [default URL parameters](#introduction/overview/url-params) (metadata)
for pagination and ordering, you can use any other parameter to query
by particular object properties

#### List All Store Applications [GET /applications.json]

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "app_id",
                  "state",
                  "version",
                  "version_date",
                  "type"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "42aa00000000000000000110",
                  "app_id": 1001,
                  "state": "active",
                  "version": "1.1.1",
                  "version_date": "2017-11-15T09:15:10.612Z",
                  "type": "storefront"
                },
                {
                  "_id": "42aa00000000000000000111",
                  "app_id": 1002,
                  "state": "active",
                  "version": "3.0.0",
                  "type": "dashboard"
                },
                {
                  "_id": "42aa00000000000000000112",
                  "app_id": 1003,
                  "state": "test",
                  "version": "2.14.0",
                  "version_date": "2017-11-14T12:00:10.612Z",
                  "type": "storefront"
                },
                {
                  "_id": "42aa00000000000000000113",
                  "app_id": 1004,
                  "state": "inactive",
                  "version": "2.0.23",
                  "version_date": "2017-12-15T00:15:10.612Z",
                  "type": "module_package"
                },
                {
                  "_id": "42aa00000000000000000114",
                  "app_id": 1005,
                  "state": "active",
                  "version": "3.1.3",
                  "version_date": "2017-12-20T00:15:10.612Z",
                  "type": "external"
                }
              ]
            }

#### Pagination And Ordering [GET]

+ Parameters
    + limit: 3 (number, optional) - Max number of objects to return
    + offset: 3 (number, optional) - First entry to return
    + sort: `-version_date` (string, optional) - Rules to order resultant objects
    + fields: `app_id,title` (string, optional) - Object properties to return

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 3,
                "offset": 3,
                "sort": [
                  {
                    "field": "version_date",
                    "order": -1
                  }
                ],
                "fields": [
                  "app_id",
                  "title"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "42aa00000000000000000111",
                  "app_id": 1002,
                  "title": "Products panel extension"
                }
              ]
            }

#### Find Applications [GET /applications.json{?app_id}]

+ Parameters
    + `app_id`: `1004` (string, optional) - Object property to query

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "app_id",
                  "state",
                  "version",
                  "version_date",
                  "type"
                ],
                "query": {
                  "app_id": 1004
                }
              },
              "result": [
                {
                  "_id": "42aa00000000000000000113",
                  "app_id": 1004,
                  "state": "inactive",
                  "version": "2.0.23",
                  "version_date": "2017-12-15T00:15:10.612Z",
                  "type": "module_package"
                }
              ]
            }

### New Application [/applications.json]

*/applications.json*

> Authentication<br>_POST_: **required**

Request body must obey the specifications of
[this model](#reference/applications/application-object)

#### Create New Application [POST]

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "app_id": 1002,
              "state": "active",
              "title": "Products panel extension",
              "slug": "products-panel-ext",
              "paid": true,
              "version": "3.0.0",
              "type": "dashboard",
              "load_events": [
                "products"
              ],
              "script_uri": "https://sample.mycdn.com/script.min.js"
            }

+ Response 201 (application/json)

    + Body

            {
              "_id": "42aa00000000000000000111"
            }

### Specific Application [/applications/{_id}.json]

*/applications/[_id].json*

> Authentication<br>_GET_: **optional**<br>_PATCH_, _PUT_, _DELETE_: **required**

In read requests, response body will follow
[this model](#reference/applications/application-object),
requests without authentication will receive application data without
`authentication`, `auth_scope` and `hidden_data` properties

For overwriting and editing, request body must obey the same specifications,
but especially for edit requests there are no required fields

#### Read Application [GET /applications/{application}.json]

+ Parameters
    + application: 42aa00000000000000000111 (string, required) - The application ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "_id": "42aa00000000000000000111",
              "created_at": "2017-11-19T13:10:00.612Z",
              "store_id": 100,
              "app_id": 1002,
              "state": "active",
              "title": "Products panel extension",
              "slug": "products-panel-ext",
              "paid": true,
              "payment_status": "trial",
              "version": "3.0.0",
              "type": "dashboard",
              "load_events": [
                "products"
              ],
              "script_uri": "https://sample.mycdn.com/script.min.js",
              "data": {
                "sample": 123,
                "eg": [ 1, 2, 3 ]
              }
            }

#### With Authentication [GET]

+ Parameters
    + _id: 42aa00000000000000000111 (string, required) - The application ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "_id": "42aa00000000000000000111",
              "created_at": "2017-11-19T13:10:00.612Z",
              "store_id": 100,
              "app_id": 1002,
              "state": "active",
              "title": "Products panel extension",
              "slug": "products-panel-ext",
              "paid": true,
              "payment_status": "trial",
              "version": "3.0.0",
              "type": "dashboard",
              "load_events": [
                "products"
              ],
              "script_uri": "https://sample.mycdn.com/script.min.js",
              "authentication": false,
              "data": {
                "sample": 123,
                "eg": [ 1, 2, 3 ]
              },
              "hidden_data": {
                "token": "sdkcblsdcbslkc"
              }
            }

#### Edit Application [PATCH]

+ Parameters
    + _id: 42aa00000000000000000111 (string, required) - The application ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "state": "inactive",
              "status": "paused"
            }

+ Response 204

#### Overwrite Application [PUT]

+ Parameters
    + _id: 42aa00000000000000000111 (string, required) - The application ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "app_id": 1002,
              "state": "inactive",
              "title": "Products panel extension",
              "slug": "products-panel-ext",
              "paid": true,
              "version": "3.0.0",
              "type": "dashboard",
              "load_events": [
                "products"
              ],
              "script_uri": "https://sample.mycdn.com/script.min.js",
              "status": "paused"
            }

+ Response 204

#### Remove Application [DELETE]

+ Parameters
    + _id: 42aa00000000000000000111 (string, required) - The application ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 204
