+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "name",
                  "slug",
                  "logo"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "a10000000000000000001110",
                  "name": "Brand 0",
                  "slug": "brand-zero",
                  "logo": {
                    "url": "https://mycdn.com/brand-0-logo.jpg",
                    "size": "90x70",
                    "alt": "Brand Zero"
                  }
                },
                {
                  "_id": "a10000000000000000001111",
                  "name": "Brand 1",
                  "slug": "brand-one",
                  "logo": {
                    "url": "https://mycdn.com/brand-1-logo.jpg",
                    "size": "70x70",
                    "alt": "Brand One"
                  }
                },
                {
                  "_id": "a10000000000000000001112",
                  "name": "Brand 2",
                  "slug": "brand-two"
                },
                {
                  "_id": "a10000000000000000001113",
                  "name": "Brand 3",
                  "slug": "brand-three"
                },
                {
                  "_id": "a10000000000000000001114",
                  "name": "Brand 4",
                  "slug": "brand-four",
                  "logo": {
                    "url": "https://mycdn.com/brand-4-logo.jpg",
                    "size": "70x70"
                  }
                },
                {
                  "_id": "a10000000000000000001115",
                  "name": "Brand 5",
                  "slug": "brand-five",
                  "logo": {
                    "url": "https://mycdn.com/brand-5-logo.jpg",
                    "size": "70x70"
                  }
                },
                {
                  "_id": "a10000000000000000001116",
                  "name": "Brand 6",
                  "slug": "brand-six",
                  "logo": {
                    "url": "https://mycdn.com/brand-6-logo.jpg",
                    "size": "70x70",
                    "alt": "Brand Six"
                  }
                },
                {
                  "_id": "a10000000000000000000001",
                  "name": "Shirts Example",
                  "slug": "shirts-example",
                  "logo": {
                    "url": "https://mycdn.com/shirts-example.jpg",
                    "size": "100x50"
                  }
                }
              ]
            }
