+ Parameters
    + brand: a10000000000000000000001 (string, required) - The brand ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "pt_br": "Camisetas Exemplo",
              "es_es": "Camisetas Ejemplo"
            }
