## Group Brand i18n

`.brands.i18n`

Use the **i18n** subresource to read and update
translations for an specific brand name, with up to 10 languages

### Brand i18n Object [/brands/schema/i18n.json]

+ Attributes (object)
    + `^[a-z]{2}(_[a-z]{2})?$` (string) - Translated name - Max length: **255**

#### JSON Schema [GET]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (i18n/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Name language translations",
                "type": "object",
                "additionalProperties": false,
                "minProperties": 1,
                "maxProperties": 10,
                "patternProperties": {
                    "^[a-z]{2}(_[a-z]{2})?$": {
                        "type": "string",
                        "maxLength": 255,
                        "description": "Translated name"
                    }
                }
            }

### i18n of a Brand [/brands/{brand}/i18n.json]

*/brands/[_id]/i18n.json*

> Authentication<br>_GET_, _PATCH_: **required**

#### Read Brand Name Translations [GET]

+ Parameters
    + brand: a10000000000000000000001 (string, required) - The brand ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "pt_br": "Camisetas Exemplo",
              "es_es": "Camisetas Ejemplo"
            }

#### Edit Brand Name Translations [PATCH]

+ Parameters
    + brand: a10000000000000000000001 (string, required) - The brand ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

    + Body

            {
              "it": "Camicie Esempio"
            }

+ Response 204
