+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "query": {}
              },
              "result": [
                {
                  "_id": "1234567890abcdef01291510",
                  "sku": "COD1"
                },
                {
                  "_id": "1234567890abcdef01291511",
                  "sku": "S_123456789"
                },
                {
                  "_id": "1234567890abcdef01291512",
                  "sku": "sYY7-100P"
                }
              ]
            }
