+ Request (application/json)

    + Headers

            X-Store-ID: 100

    + Attributes (object)
        + _id: 100000000000000000000012 (string, required)
            Authentication object ID

    + Body

            {
              "_id": "100000000000000000000012"
            }

+ Response 204 (application/json)
